package main

import (
	"archive/tar"
	"archive/zip"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	provenancePath = "contracts/network-flow/timezone/tzdb-2026c.provenance.json"
	vendorRoot     = "tools/networkflow-tzdb/vendor/tzdb-2026c"
	outputPath     = "internal/gen/networkflowtz/tzdata2026c.go"
)

type provenance struct {
	RulesetID string `json:"ruleset_id"`
	Source    struct {
		FileName string `json:"file_name"`
		URL      string `json:"url"`
		Size     int64  `json:"size_bytes"`
		SHA256   string `json:"sha256"`
	} `json:"source_archive"`
	Signature struct {
		FileName string `json:"file_name"`
		URL      string `json:"url"`
		Size     int64  `json:"size_bytes"`
		SHA256   string `json:"sha256"`
	} `json:"detached_signature"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "generate Network Flow tzdb:", err)
		os.Exit(1)
	}
}

func run() error {
	raw, err := os.ReadFile(provenancePath)
	if err != nil {
		return err
	}
	var owner provenance
	if err := json.Unmarshal(raw, &owner); err != nil {
		return err
	}
	if owner.RulesetID != "tzdb-2026c" {
		return fmt.Errorf("unexpected ruleset_id %q", owner.RulesetID)
	}
	if err := os.MkdirAll(vendorRoot, 0o755); err != nil {
		return err
	}
	archivePath := filepath.Join(vendorRoot, owner.Source.FileName)
	signaturePath := filepath.Join(vendorRoot, owner.Signature.FileName)
	if err := fetchAndVerify(archivePath, owner.Source.URL, owner.Source.Size, owner.Source.SHA256); err != nil {
		return fmt.Errorf("source archive: %w", err)
	}
	if err := fetchAndVerify(signaturePath, owner.Signature.URL, owner.Signature.Size, owner.Signature.SHA256); err != nil {
		return fmt.Errorf("detached signature: %w", err)
	}
	tempRoot, err := os.MkdirTemp("", "cartulary-tzdb-2026c-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tempRoot)
	sourceRoot := filepath.Join(tempRoot, "source")
	zoneRoot := filepath.Join(tempRoot, "zoneinfo")
	if err := os.MkdirAll(sourceRoot, 0o755); err != nil {
		return err
	}
	if err := extractSources(archivePath, sourceRoot); err != nil {
		return err
	}
	if err := os.MkdirAll(zoneRoot, 0o755); err != nil {
		return err
	}
	zic := os.Getenv("ZIC")
	if zic == "" {
		zic = "/usr/sbin/zic"
	}
	inputs := []string{"africa", "antarctica", "asia", "australasia", "europe", "northamerica", "southamerica", "etcetera", "backward", "factory"}
	args := []string{"-b", "fat", "-d", zoneRoot}
	for _, input := range inputs {
		args = append(args, filepath.Join(sourceRoot, input))
	}
	command := exec.Command(zic, args...)
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("zic failed: %w: %s", err, strings.TrimSpace(string(output)))
	}
	zoneZip, err := buildZoneZip(zoneRoot)
	if err != nil {
		return err
	}
	source := fmt.Sprintf("// Code generated by tools/networkflow-tzdb; DO NOT EDIT.\n\npackage networkflowtz\n\nconst RulesetID = %q\nconst ZoneinfoZip = %s\n", owner.RulesetID, strconv.Quote(string(zoneZip)))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, formatted, 0o644)
}

func fetchAndVerify(path, url string, size int64, digest string) error {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		client := &http.Client{Timeout: 30 * time.Second}
		response, err := client.Get(url)
		if err != nil {
			return err
		}
		defer response.Body.Close()
		if response.StatusCode != http.StatusOK {
			return fmt.Errorf("download returned HTTP %d", response.StatusCode)
		}
		content, err := io.ReadAll(io.LimitReader(response.Body, size+1))
		if err != nil {
			return err
		}
		if int64(len(content)) != size {
			return fmt.Errorf("download size %d, want %d", len(content), size)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return err
		}
	} else if err != nil {
		return err
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if int64(len(content)) != size {
		return fmt.Errorf("size %d, want %d", len(content), size)
	}
	actual := sha256.Sum256(content)
	if hex.EncodeToString(actual[:]) != digest {
		return fmt.Errorf("SHA-256 does not match immutable provenance")
	}
	return nil
}

func extractSources(archivePath, destination string) error {
	file, err := os.Open(archivePath)
	if err != nil {
		return err
	}
	defer file.Close()
	gzipReader, err := gzip.NewReader(file)
	if err != nil {
		return err
	}
	defer gzipReader.Close()
	allowed := map[string]struct{}{}
	for _, name := range []string{"africa", "antarctica", "asia", "australasia", "europe", "northamerica", "southamerica", "etcetera", "backward", "factory", "LICENSE", "version"} {
		allowed[name] = struct{}{}
	}
	reader := tar.NewReader(gzipReader)
	for {
		header, err := reader.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		if _, ok := allowed[header.Name]; !ok {
			continue
		}
		if header.Typeflag != tar.TypeReg || header.Size < 0 || header.Size > 2<<20 {
			return fmt.Errorf("invalid source member %q", header.Name)
		}
		content, err := io.ReadAll(io.LimitReader(reader, header.Size+1))
		if err != nil || int64(len(content)) != header.Size {
			return fmt.Errorf("read source member %q", header.Name)
		}
		if err := os.WriteFile(filepath.Join(destination, header.Name), content, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func buildZoneZip(root string) ([]byte, error) {
	paths := []string{}
	if err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		paths = append(paths, filepath.ToSlash(relative))
		return nil
	}); err != nil {
		return nil, err
	}
	sort.Strings(paths)
	var output strings.Builder
	writer := zip.NewWriter(&output)
	for _, relative := range paths {
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(relative)))
		if err != nil {
			return nil, err
		}
		header := &zip.FileHeader{Name: relative, Method: zip.Store}
		header.SetMode(0o644)
		header.Modified = time.Unix(0, 0).UTC()
		entry, err := writer.CreateHeader(header)
		if err != nil {
			return nil, err
		}
		if _, err := entry.Write(content); err != nil {
			return nil, err
		}
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	return []byte(output.String()), nil
}
