import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";

const inputs = ["tools/workspace_layout.json", "tools/schemas/cartulary.workspace_layout.v1.schema.json", "tools/harness/workspace/layout.mjs"];
export const projectionPaths = ["tools/workspace_layout.generated.sh", "tools/workspace_layout.generated.mk", "tools/workspace_layout.generated.mjs"];
const marker = "Code generated by tools/harness/workspace/layout.mjs; DO NOT EDIT.";
const digest = (value) => createHash("sha256").update(value).digest("hex");

export function validateLayout(owner, schema) {
  const validate = new Ajv2020({ strict: false }).compile(schema);
  if (!validate(owner)) throw new Error(`workspace layout schema: ${JSON.stringify(validate.errors)}`);
  const byID = new Map();
  const paths = new Set();
  for (const entry of owner.directories) {
    const parts = entry.path.split("/");
    if (byID.has(entry.id) || paths.has(entry.path)) throw new Error("duplicate workspace directory");
    if (parts.some((part) => !part || part === "." || part === "..") ||
        (entry.path.includes("*") && !/^packages\/\*\/node_modules(?:\/\.vite(?:-temp)?)?$/u.test(entry.path))) throw new Error(`unsafe directory: ${entry.path}`);
    // Source ancestors can never be cleanup roots. Tracked-source overlap is also
    // checked at execution, including source files added since generation.
    if (["apps", "apps/web", "build", ".cartulary", ".cache", "packages", "internal", "internal/platform", "internal/platform/httpapi", "internal/platform/httpapi/webassets", "internal/platform/httpapi/webassets/assets"].includes(entry.path) || /^(?:\.git|docs|cmd|configs|contracts|db|scripts|tools)(?:\/|$)/u.test(entry.path)) throw new Error(`source ancestor: ${entry.path}`);
    if ((entry.state === "legacy") !== (entry.producers.length === 0)) throw new Error(`legacy directories cannot have producers: ${entry.id}`);
    byID.set(entry.id, entry); paths.add(entry.path);
  }
  for (const entry of owner.directories) {
    const ancestors = owner.directories.filter((other) => entry.path.startsWith(`${other.path}/`)).sort((a, b) => b.path.length - a.path.length);
    if ((ancestors[0]?.id ?? undefined) !== entry.parent) throw new Error(`undeclared directory overlap: ${entry.id}`);
    if (entry.parent && byID.get(entry.parent).tier === "clean" && entry.tier !== "clean") throw new Error(`inconsistent cleanup tier: ${entry.id}`);
  }
  return owner;
}

export function renderLayout(root) {
  const owner = validateLayout(JSON.parse(readFileSync(path.join(root, inputs[0]))), JSON.parse(readFileSync(path.join(root, inputs[1]))));
  const checksums = inputs.map((input) => `${digest(readFileSync(path.join(root, input)))}  ${input}`);
  const current = owner.directories.filter((entry) => entry.state === "current");
  return new Map([
    [projectionPaths[0], `# ${marker}\n# shellcheck shell=bash\n# Shared declarations are consumed by sourced callers.\n# shellcheck disable=SC2034\nCARTULARY_LAYOUT_DIGESTS='${checksums.join("\n")}'\n` + current.map((entry) => `CARTULARY_LAYOUT_${entry.id.toUpperCase()}='${entry.path}'\n`).join("") + `declare -a CARTULARY_CLEANUP_ENTRIES=(\n${owner.directories.map((entry) => `  '${entry.id}|${entry.tier}|${entry.path}'`).join("\n")}\n)\n`],
    [projectionPaths[1], `# ${marker}\n` + current.map((entry) => `LAYOUT_${entry.id.toUpperCase()} := ${entry.path}\n`).join("")],
    [projectionPaths[2], `// ${marker}\nexport const workspaceLayout = Object.freeze(${JSON.stringify(Object.fromEntries(current.map((entry) => [entry.id, entry.path])), null, 2)});\n`],
  ]);
}

export function generateLayout(root, { check = false } = {}) {
  for (const [file, content] of renderLayout(root)) {
    if (check) { if (readFileSync(path.join(root, file), "utf8") !== content) throw new Error(`stale workspace projection: ${file}`); }
    else writeFileSync(path.join(root, file), content);
  }
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateLayout(path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../.."), { check: process.argv.includes("--check") });
}
