package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type artifact struct {
	Path   string
	JSON   string
	SHA256 string
}

type family struct {
	Dir         string
	GoName      string
	TSName      string
	Artifacts   []artifact
	OutputOrder int
}

func main() {
	root, err := repoRoot()
	if err != nil {
		fatal(err)
	}

	families := []family{
		{Dir: "openapi", GoName: "OpenAPIArtifacts", TSName: "openAPIArtifacts", OutputOrder: 0},
		{Dir: "ws", GoName: "WSArtifacts", TSName: "wsArtifacts", OutputOrder: 1},
		{Dir: "view-schemas", GoName: "ViewSchemaArtifacts", TSName: "viewSchemaArtifacts", OutputOrder: 2},
		{Dir: "errors", GoName: "ErrorArtifacts", TSName: "errorArtifacts", OutputOrder: 3},
		{Dir: "extensions", GoName: "ExtensionArtifacts", TSName: "extensionArtifacts", OutputOrder: 4},
	}

	for index := range families {
		artifacts, err := collectArtifacts(root, families[index].Dir)
		if err != nil {
			fatal(err)
		}
		families[index].Artifacts = artifacts
	}

	if err := writeGo(root, families); err != nil {
		fatal(err)
	}
	if err := writeTypeScript(root, families); err != nil {
		fatal(err)
	}
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repo root from %q", dir)
		}
		dir = parent
	}
}

func collectArtifacts(root, familyDir string) ([]artifact, error) {
	baseDir := filepath.Join(root, "contracts", familyDir)
	var artifacts []artifact

	if err := filepath.WalkDir(baseDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}

		name := entry.Name()
		if name == ".gitkeep" || !supportedContractFile(name) {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}

		canonicalJSON, err := canonicalize(data)
		if err != nil {
			return fmt.Errorf("canonicalize %s: %w", path, err)
		}

		relativePath, err := filepath.Rel(root, path)
		if err != nil {
			return fmt.Errorf("relativize %s: %w", path, err)
		}

		hash := sha256.Sum256([]byte(canonicalJSON))
		artifacts = append(artifacts, artifact{
			Path:   filepath.ToSlash(relativePath),
			JSON:   canonicalJSON,
			SHA256: hex.EncodeToString(hash[:]),
		})
		return nil
	}); err != nil {
		return nil, err
	}

	sort.Slice(artifacts, func(i, j int) bool {
		return artifacts[i].Path < artifacts[j].Path
	})

	return artifacts, nil
}

func supportedContractFile(name string) bool {
	switch strings.ToLower(filepath.Ext(name)) {
	case ".json", ".yaml", ".yml":
		return true
	default:
		return false
	}
}

func canonicalize(data []byte) (string, error) {
	var decoded any
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	if err := decoder.Decode(&decoded); err != nil {
		return "", fmt.Errorf("decode contract input as JSON or JSON-compatible YAML: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); err == nil {
		return "", fmt.Errorf("contract input must contain exactly one JSON document")
	}

	normalized := normalize(decoded)
	canonicalJSON, err := json.Marshal(normalized)
	if err != nil {
		return "", err
	}

	return string(canonicalJSON), nil
}

func normalize(value any) any {
	switch typed := value.(type) {
	case map[string]any:
		normalized := make(map[string]any, len(typed))
		for key, item := range typed {
			normalized[key] = normalize(item)
		}
		return normalized
	case map[any]any:
		normalized := make(map[string]any, len(typed))
		for key, item := range typed {
			normalized[fmt.Sprint(key)] = normalize(item)
		}
		return normalized
	case []any:
		items := make([]any, len(typed))
		for index, item := range typed {
			items[index] = normalize(item)
		}
		return items
	default:
		return typed
	}
}

func writeGo(root string, families []family) error {
	var buffer bytes.Buffer

	buffer.WriteString("// Code generated by tools/contractgen; DO NOT EDIT.\n\n")
	buffer.WriteString("package contracts\n\n")
	buffer.WriteString("type Artifact struct {\n")
	buffer.WriteString("\tPath string `json:\"path\"`\n")
	buffer.WriteString("\tJSON string `json:\"json\"`\n")
	buffer.WriteString("\tSHA256 string `json:\"sha256\"`\n")
	buffer.WriteString("}\n\n")
	buffer.WriteString("func indexArtifacts(artifacts []Artifact) map[string]Artifact {\n")
	buffer.WriteString("\tindexed := make(map[string]Artifact, len(artifacts))\n")
	buffer.WriteString("\tfor _, artifact := range artifacts {\n")
	buffer.WriteString("\t\tindexed[artifact.Path] = artifact\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\treturn indexed\n")
	buffer.WriteString("}\n\n")
	buffer.WriteString("func mergeArtifactIndexes(artifactSets ...[]Artifact) map[string]Artifact {\n")
	buffer.WriteString("\ttotal := 0\n")
	buffer.WriteString("\tfor _, artifacts := range artifactSets {\n")
	buffer.WriteString("\t\ttotal += len(artifacts)\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\tindexed := make(map[string]Artifact, total)\n")
	buffer.WriteString("\tfor _, artifacts := range artifactSets {\n")
	buffer.WriteString("\t\tfor _, artifact := range artifacts {\n")
	buffer.WriteString("\t\t\tindexed[artifact.Path] = artifact\n")
	buffer.WriteString("\t\t}\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\treturn indexed\n")
	buffer.WriteString("}\n\n")

	for _, current := range families {
		buffer.WriteString("var ")
		buffer.WriteString(current.GoName)
		buffer.WriteString(" = []Artifact{\n")
		for _, currentArtifact := range current.Artifacts {
			buffer.WriteString("\t{\n")
			buffer.WriteString("\t\tPath: ")
			buffer.WriteString(strconv.Quote(currentArtifact.Path))
			buffer.WriteString(",\n")
			buffer.WriteString("\t\tJSON: ")
			buffer.WriteString(strconv.Quote(currentArtifact.JSON))
			buffer.WriteString(",\n")
			buffer.WriteString("\t\tSHA256: ")
			buffer.WriteString(strconv.Quote(currentArtifact.SHA256))
			buffer.WriteString(",\n")
			buffer.WriteString("\t},\n")
		}
		buffer.WriteString("}\n\n")

		buffer.WriteString("var ")
		buffer.WriteString(current.GoName)
		buffer.WriteString("Index = indexArtifacts(")
		buffer.WriteString(current.GoName)
		buffer.WriteString(")\n\n")
	}

	buffer.WriteString("var ContractArtifactIndex = mergeArtifactIndexes(\n")
	for _, current := range families {
		buffer.WriteString("\t")
		buffer.WriteString(current.GoName)
		buffer.WriteString(",\n")
	}
	buffer.WriteString(")\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return fmt.Errorf("format generated Go: %w", err)
	}

	outputPath := filepath.Join(root, "internal", "gen", "contracts", "contracts_gen.go")
	return os.WriteFile(outputPath, formatted, 0o644)
}

func writeTypeScript(root string, families []family) error {
	contractsPath := filepath.Join(root, "packages", "protocol-ts", "src", "generated", "contracts.ts")
	indexPath := filepath.Join(root, "packages", "protocol-ts", "src", "generated", "index.ts")

	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by tools/contractgen; DO NOT EDIT.\n\n")
	buffer.WriteString("export type Artifact = {\n")
	buffer.WriteString("  readonly path: string;\n")
	buffer.WriteString("  readonly json: string;\n")
	buffer.WriteString("  readonly sha256: string;\n")
	buffer.WriteString("};\n\n")
	buffer.WriteString("function indexArtifacts(\n")
	buffer.WriteString("  artifacts: readonly Artifact[],\n")
	buffer.WriteString("): Readonly<Record<string, Artifact>> {\n")
	buffer.WriteString("  return Object.freeze(\n")
	buffer.WriteString("    Object.fromEntries(\n")
	buffer.WriteString("      artifacts.map((artifact) => [artifact.path, artifact]),\n")
	buffer.WriteString("    ) as Record<string, Artifact>,\n")
	buffer.WriteString("  );\n")
	buffer.WriteString("}\n\n")

	for _, current := range families {
		buffer.WriteString("export const ")
		buffer.WriteString(current.TSName)
		buffer.WriteString(": readonly Artifact[] = [\n")
		for _, currentArtifact := range current.Artifacts {
			buffer.WriteString("  {\n")
			buffer.WriteString("    path: ")
			buffer.WriteString(marshalJSONString(currentArtifact.Path))
			buffer.WriteString(",\n")
			buffer.WriteString("    json: ")
			buffer.WriteString(marshalJSONString(currentArtifact.JSON))
			buffer.WriteString(",\n")
			buffer.WriteString("    sha256: ")
			buffer.WriteString(marshalJSONString(currentArtifact.SHA256))
			buffer.WriteString(",\n")
			buffer.WriteString("  },\n")
		}
		buffer.WriteString("];\n\n")

		buffer.WriteString("export const ")
		buffer.WriteString(current.TSName)
		buffer.WriteString("Index = indexArtifacts(")
		buffer.WriteString(current.TSName)
		buffer.WriteString(");\n\n")
	}

	buffer.WriteString("export const contractArtifacts = {\n")
	sortedFamilies := append([]family(nil), families...)
	sort.Slice(sortedFamilies, func(i, j int) bool {
		return sortedFamilies[i].OutputOrder < sortedFamilies[j].OutputOrder
	})
	for _, current := range sortedFamilies {
		buffer.WriteString("  ")
		buffer.WriteString(current.TSName)
		buffer.WriteString(",\n")
	}
	buffer.WriteString("} as const;\n")
	buffer.WriteString("\n")
	buffer.WriteString("export const contractArtifactIndex = Object.freeze({\n")
	for _, current := range sortedFamilies {
		buffer.WriteString("  ...")
		buffer.WriteString(current.TSName)
		buffer.WriteString("Index,\n")
	}
	buffer.WriteString("}) as Readonly<Record<string, Artifact>>;\n")

	indexContent := "// Code generated by tools/contractgen; DO NOT EDIT.\n\nexport * from \"./contracts.js\";\n"

	if err := os.WriteFile(contractsPath, buffer.Bytes(), 0o644); err != nil {
		return err
	}
	return os.WriteFile(indexPath, []byte(indexContent), 0o644)
}

func marshalJSONString(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		fatal(fmt.Errorf("marshal JSON string: %w", err))
	}
	return string(encoded)
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "contractgen: %v\n", err)
	os.Exit(1)
}
