package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const (
	partyFieldRegistrySchemaID      = "cartulary.parties.field_registry.v1"
	partyMutationHashAlgorithmID    = "cartulary.parties.mutation_request_hash.v1"
	partyViewSchemaID               = "cartulary.view.parties.v1"
	timezoneNameRegistrySchemaID    = "cartulary.timezone_name_registry.v1"
	timezoneNameRegistrySnapshotID  = "iana.tzdb.2026c"
	timezoneNameRegistryDigestInput = "utf8_name_tab_kind_lf_sorted_bytewise"
)

type partyFieldRegistry struct {
	SchemaID     string               `json:"schema_id"`
	AlgorithmID  string               `json:"algorithm_id"`
	ViewSchemaID string               `json:"view_schema_id"`
	Fields       []partyFieldContract `json:"fields"`
}

type partyFieldContract struct {
	FieldKey             string   `json:"field_key"`
	SourceColumn         string   `json:"source_column"`
	Required             bool     `json:"required"`
	CreateOmission       string   `json:"create_omission"`
	Clearable            bool     `json:"clearable"`
	StringContractID     *string  `json:"string_contract_id"`
	MaxUnicodeScalars    *int     `json:"max_unicode_scalars"`
	EnumValues           []string `json:"enum_values"`
	StoredValuePosture   string   `json:"stored_value_posture"`
	EqualityPosture      string   `json:"equality_posture"`
	ClaimRole            *string  `json:"claim_role"`
	CanonicalHashPosture string   `json:"canonical_hash_posture"`
	ConflictClass        string   `json:"conflict_class"`
}

type timezoneNameRegistry struct {
	SchemaID                 string                   `json:"schema_id"`
	SnapshotID               string                   `json:"snapshot_id"`
	ProvenanceSchemaID       string                   `json:"provenance_schema_id"`
	Normalization            string                   `json:"normalization"`
	LinkPosture              string                   `json:"link_posture"`
	IdentifierCount          int                      `json:"identifier_count"`
	IdentifierSetSHA256      string                   `json:"identifier_set_sha256"`
	IdentifierSetDigestInput string                   `json:"identifier_set_digest_input"`
	Identifiers              []timezoneNameIdentifier `json:"identifiers"`
}

type timezoneNameIdentifier struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

type timezoneNameRegistryProvenance struct {
	SchemaID                            string          `json:"schema_id"`
	RegistryID                          string          `json:"registry_id"`
	SnapshotID                          string          `json:"snapshot_id"`
	IANAVersion                         string          `json:"iana_version"`
	SourceArchive                       json.RawMessage `json:"source_archive"`
	DetachedSignature                   json.RawMessage `json:"detached_signature"`
	SourceFiles                         []string        `json:"source_files"`
	Selection                           string          `json:"selection"`
	HostTimezoneDatabaseAuthoritative   bool            `json:"host_timezone_database_authoritative"`
	RetainPreviouslyAdmittedIdentifiers bool            `json:"retain_previously_admitted_identifiers"`
}

func writePartyFieldRegistryGo(root string) error {
	var registry partyFieldRegistry
	if err := decodeStrictContractFile(filepath.Join(root, "contracts", "parties", "field_registry.v1.json"), &registry); err != nil {
		return err
	}
	if err := validatePartyFieldRegistry(root, registry); err != nil {
		return err
	}

	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by tools/contractgen; DO NOT EDIT.\n\n")
	buffer.WriteString("package partypolicy\n\n")
	fmt.Fprintf(&buffer, "const FieldRegistrySchemaID = %s\n", strconv.Quote(registry.SchemaID))
	fmt.Fprintf(&buffer, "const MutationRequestHashAlgorithmID = %s\n", strconv.Quote(registry.AlgorithmID))
	fmt.Fprintf(&buffer, "const ViewSchemaID = %s\n\n", strconv.Quote(registry.ViewSchemaID))
	buffer.WriteString("type Field struct {\n")
	buffer.WriteString("\tFieldKey string\n\tSourceColumn string\n\tRequired bool\n\tCreateOmission string\n\tClearable bool\n")
	buffer.WriteString("\tStringContractID string\n\tMaxUnicodeScalars int\n\tEnumValues []string\n")
	buffer.WriteString("\tStoredValuePosture string\n\tEqualityPosture string\n\tClaimRole string\n")
	buffer.WriteString("\tCanonicalHashPosture string\n\tConflictClass string\n")
	buffer.WriteString("}\n\n")
	buffer.WriteString("func FieldKeys() []string {\n\treturn []string{\n")
	for _, field := range registry.Fields {
		fmt.Fprintf(&buffer, "\t\t%s,\n", strconv.Quote(field.FieldKey))
	}
	buffer.WriteString("\t}\n}\n\n")
	buffer.WriteString("func LookupField(fieldKey string) (Field, bool) {\n\tswitch fieldKey {\n")
	for _, field := range registry.Fields {
		fmt.Fprintf(&buffer, "\tcase %s:\n\t\treturn Field{\n", strconv.Quote(field.FieldKey))
		fmt.Fprintf(&buffer, "\t\t\tFieldKey: %s,\n", strconv.Quote(field.FieldKey))
		fmt.Fprintf(&buffer, "\t\t\tSourceColumn: %s,\n", strconv.Quote(field.SourceColumn))
		fmt.Fprintf(&buffer, "\t\t\tRequired: %t,\n", field.Required)
		fmt.Fprintf(&buffer, "\t\t\tCreateOmission: %s,\n", strconv.Quote(field.CreateOmission))
		fmt.Fprintf(&buffer, "\t\t\tClearable: %t,\n", field.Clearable)
		fmt.Fprintf(&buffer, "\t\t\tStringContractID: %s,\n", strconv.Quote(optionalString(field.StringContractID)))
		fmt.Fprintf(&buffer, "\t\t\tMaxUnicodeScalars: %d,\n", optionalInt(field.MaxUnicodeScalars))
		if len(field.EnumValues) > 0 {
			buffer.WriteString("\t\t\tEnumValues: []string{")
			for index, value := range field.EnumValues {
				if index > 0 {
					buffer.WriteString(", ")
				}
				buffer.WriteString(strconv.Quote(value))
			}
			buffer.WriteString("},\n")
		}
		fmt.Fprintf(&buffer, "\t\t\tStoredValuePosture: %s,\n", strconv.Quote(field.StoredValuePosture))
		fmt.Fprintf(&buffer, "\t\t\tEqualityPosture: %s,\n", strconv.Quote(field.EqualityPosture))
		fmt.Fprintf(&buffer, "\t\t\tClaimRole: %s,\n", strconv.Quote(optionalString(field.ClaimRole)))
		fmt.Fprintf(&buffer, "\t\t\tCanonicalHashPosture: %s,\n", strconv.Quote(field.CanonicalHashPosture))
		fmt.Fprintf(&buffer, "\t\t\tConflictClass: %s,\n", strconv.Quote(field.ConflictClass))
		buffer.WriteString("\t\t}, true\n")
	}
	buffer.WriteString("\tdefault:\n\t\treturn Field{}, false\n\t}\n}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return fmt.Errorf("format generated Party field registry: %w", err)
	}
	return stageGeneratedFile(filepath.Join(root, "internal", "gen", "partypolicy", "registry_gen.go"), formatted, 0o644)
}

func validatePartyFieldRegistry(root string, registry partyFieldRegistry) error {
	if registry.SchemaID != partyFieldRegistrySchemaID || registry.AlgorithmID != partyMutationHashAlgorithmID || registry.ViewSchemaID != partyViewSchemaID {
		return fmt.Errorf("party field registry identities do not match the adopted projection")
	}
	expectedKeys := []string{
		"party.display_name",
		"party.party_kind",
		"party.organization_name",
		"party.role_title",
		"party.primary_email",
		"party.timezone_name",
		"party.external_ref",
		"party.notes",
	}
	if len(registry.Fields) != len(expectedKeys) {
		return fmt.Errorf("party field registry must contain exactly %d fields", len(expectedKeys))
	}
	for index, expectedKey := range expectedKeys {
		field := registry.Fields[index]
		if field.FieldKey != expectedKey {
			return fmt.Errorf("party field registry field %d must be %s", index+1, expectedKey)
		}
		expectedClearable := index >= 2
		if field.Clearable != expectedClearable || field.Required == expectedClearable {
			return fmt.Errorf("party field %s required/clearable posture is inconsistent", field.FieldKey)
		}
		if field.SourceColumn == "" || field.StoredValuePosture == "" || field.EqualityPosture == "" || field.CanonicalHashPosture == "" || field.ConflictClass == "" {
			return fmt.Errorf("party field %s contains an empty required projection value", field.FieldKey)
		}
	}
	return validatePartyViewClearability(root, registry)
}

func validatePartyViewClearability(root string, registry partyFieldRegistry) error {
	raw, err := os.ReadFile(filepath.Join(root, "contracts", "view-schemas", "cartulary.view.parties.v1.json"))
	if err != nil {
		return fmt.Errorf("read Party view schema: %w", err)
	}
	if err := rejectDuplicateJSONMembers(raw); err != nil {
		return fmt.Errorf("decode Party view schema: %w", err)
	}
	var document struct {
		ViewSchemaID string `json:"view_schema_id"`
		Fields       []struct {
			FieldKey  string `json:"field_key"`
			Clearable bool   `json:"clearable"`
		} `json:"fields"`
	}
	if err := json.Unmarshal(raw, &document); err != nil {
		return fmt.Errorf("decode Party view schema: %w", err)
	}
	if document.ViewSchemaID != registry.ViewSchemaID {
		return fmt.Errorf("party view schema identity does not match field registry")
	}
	clearability := make(map[string]bool, len(document.Fields))
	for _, field := range document.Fields {
		clearability[field.FieldKey] = field.Clearable
	}
	for _, field := range registry.Fields {
		if projected, found := clearability[field.FieldKey]; !found || projected != field.Clearable {
			return fmt.Errorf("party view field %s clearability does not match field registry", field.FieldKey)
		}
	}
	return nil
}

func writeTimezoneNameRegistryGo(root string) error {
	var registry timezoneNameRegistry
	if err := decodeStrictContractFile(filepath.Join(root, "contracts", "string-contracts", "timezone_name_registry.v1.json"), &registry); err != nil {
		return err
	}
	var provenance timezoneNameRegistryProvenance
	if err := decodeStrictContractFile(filepath.Join(root, "contracts", "string-contracts", "timezone_name_registry_provenance.v1.json"), &provenance); err != nil {
		return err
	}
	if err := validateTimezoneNameRegistry(registry, provenance); err != nil {
		return err
	}

	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by tools/contractgen; DO NOT EDIT.\n\n")
	buffer.WriteString("package stringcontracts\n\n")
	fmt.Fprintf(&buffer, "const TimezoneNameRegistrySchemaID = %s\n", strconv.Quote(registry.SchemaID))
	fmt.Fprintf(&buffer, "const TimezoneNameRegistrySnapshotID = %s\n", strconv.Quote(registry.SnapshotID))
	fmt.Fprintf(&buffer, "const TimezoneNameRegistryIdentifierSetSHA256 = %s\n", strconv.Quote(registry.IdentifierSetSHA256))
	fmt.Fprintf(&buffer, "const TimezoneNameRegistryIdentifierCount = %d\n\n", registry.IdentifierCount)
	buffer.WriteString("type TimezoneNameKind string\n\n")
	buffer.WriteString("const (\n\tTimezoneNameKindZone TimezoneNameKind = \"zone\"\n\tTimezoneNameKindLink TimezoneNameKind = \"link\"\n)\n\n")
	buffer.WriteString("func LookupTimezoneName(name string) (TimezoneNameKind, bool) {\n\tswitch name {\n")
	for _, identifier := range registry.Identifiers {
		kind := "TimezoneNameKindZone"
		if identifier.Kind == "link" {
			kind = "TimezoneNameKindLink"
		}
		fmt.Fprintf(&buffer, "\tcase %s:\n\t\treturn %s, true\n", strconv.Quote(identifier.Name), kind)
	}
	buffer.WriteString("\tdefault:\n\t\treturn \"\", false\n\t}\n}\n\n")
	buffer.WriteString("func TimezoneNames() []string {\n\treturn []string{\n")
	for _, identifier := range registry.Identifiers {
		fmt.Fprintf(&buffer, "\t\t%s,\n", strconv.Quote(identifier.Name))
	}
	buffer.WriteString("\t}\n}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return fmt.Errorf("format generated timezone-name registry: %w", err)
	}
	return stageGeneratedFile(filepath.Join(root, "internal", "gen", "stringcontracts", "timezone_name_registry_gen.go"), formatted, 0o644)
}

func validateTimezoneNameRegistry(registry timezoneNameRegistry, provenance timezoneNameRegistryProvenance) error {
	if registry.SchemaID != timezoneNameRegistrySchemaID || registry.SnapshotID != timezoneNameRegistrySnapshotID {
		return fmt.Errorf("timezone-name registry identities do not match the adopted projection")
	}
	if provenance.SchemaID != registry.ProvenanceSchemaID || provenance.RegistryID != registry.SchemaID || provenance.SnapshotID != registry.SnapshotID || provenance.IANAVersion != "2026c" {
		return fmt.Errorf("timezone-name registry provenance does not match the registry")
	}
	if registry.IdentifierSetDigestInput != timezoneNameRegistryDigestInput || registry.IdentifierCount != len(registry.Identifiers) || registry.IdentifierCount == 0 {
		return fmt.Errorf("timezone-name registry count or digest input is invalid")
	}
	hasher := sha256.New()
	previous := ""
	for index, identifier := range registry.Identifiers {
		if identifier.Name == "" || (identifier.Kind != "zone" && identifier.Kind != "link") {
			return fmt.Errorf("timezone-name registry identifier %d is invalid", index+1)
		}
		if index > 0 && strings.Compare(previous, identifier.Name) >= 0 {
			return fmt.Errorf("timezone-name registry identifiers must be unique and sorted bytewise")
		}
		previous = identifier.Name
		_, _ = fmt.Fprintf(hasher, "%s\t%s\n", identifier.Name, identifier.Kind)
	}
	if digest := hex.EncodeToString(hasher.Sum(nil)); digest != registry.IdentifierSetSHA256 {
		return fmt.Errorf("timezone-name registry digest mismatch: got %s", digest)
	}
	return nil
}

func decodeStrictContractFile(path string, destination any) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if err := rejectDuplicateJSONMembers(raw); err != nil {
		return fmt.Errorf("decode %s: %w", path, err)
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil {
		return fmt.Errorf("decode %s: %w", path, err)
	}
	var extra any
	if err := decoder.Decode(&extra); err == nil || (err != nil && err != io.EOF) {
		return fmt.Errorf("decode %s: expected exactly one JSON document", path)
	}
	return nil
}

func optionalString(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

func optionalInt(value *int) int {
	if value == nil {
		return 0
	}
	return *value
}
