package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

const viewContractProjectionOutput = "packages/view-contracts/src/generated/view-contract-projection.ts"

// writeViewContractProjectionTypeScript emits the browser-facing normalized
// projection only after the authored view-schema family has passed its shape,
// cross-document, field-reference, and Inspector-registry validation.
func writeViewContractProjectionTypeScript(root string) error {
	indexPath := filepath.Join(root, "contracts", "view-schemas", "index.json")
	rawIndex, err := os.ReadFile(indexPath)
	if err != nil {
		return fmt.Errorf("read view schema index for browser projection: %w", err)
	}
	indexValue, err := decodeContract(rawIndex)
	if err != nil {
		return fmt.Errorf("decode view schema index for browser projection: %w", err)
	}
	index, err := asObject(indexValue, "contracts/view-schemas/index.json")
	if err != nil {
		return err
	}
	entries, err := objectArray(index["view_schemas"], "view_schemas")
	if err != nil {
		return err
	}

	projection := make([]any, 0, len(entries))
	for index, registryEntry := range entries {
		label := fmt.Sprintf("view_schemas[%d]", index+1)
		artifactPath, err := requiredString(registryEntry, "artifact_path", label)
		if err != nil {
			return err
		}
		rawSchema, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(artifactPath)))
		if err != nil {
			return fmt.Errorf("read %s for browser projection: %w", artifactPath, err)
		}
		schemaValue, err := decodeContract(rawSchema)
		if err != nil {
			return fmt.Errorf("decode %s for browser projection: %w", artifactPath, err)
		}
		schema, err := asObject(schemaValue, artifactPath)
		if err != nil {
			return err
		}
		entry, err := normalizeViewContractProjectionEntry(schema, registryEntry, artifactPath)
		if err != nil {
			return err
		}
		projection = append(projection, entry)
	}

	encoded, err := json.MarshalIndent(projection, "", "  ")
	if err != nil {
		return fmt.Errorf("encode browser view-contract projection: %w", err)
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by tools/contractgen; DO NOT EDIT.\n\n")
	source.WriteString("function deepFreeze<Value>(value: Value): Value {\n")
	source.WriteString("  if (value !== null && typeof value === \"object\" && !Object.isFrozen(value)) {\n")
	source.WriteString("    for (const child of Object.values(value)) deepFreeze(child);\n")
	source.WriteString("    Object.freeze(value);\n")
	source.WriteString("  }\n")
	source.WriteString("  return value;\n")
	source.WriteString("}\n\nconst value = ")
	source.Write(encoded)
	source.WriteString(" as const;\n\nexport const viewContractProjection = deepFreeze(value);\n")
	return stageGeneratedFile(
		filepath.Join(root, filepath.FromSlash(viewContractProjectionOutput)),
		source.Bytes(),
		0o644,
	)
}

func normalizeViewContractProjectionEntry(schema, registry map[string]any, source string) (map[string]any, error) {
	viewSchemaID, err := requiredString(schema, "view_schema_id", source)
	if err != nil {
		return nil, err
	}
	title, err := requiredString(schema, "title", source)
	if err != nil {
		return nil, err
	}
	surfaceKind, err := requiredString(schema, "surface_kind", source)
	if err != nil {
		return nil, err
	}
	surfaceStatus, err := requiredString(registry, "surface_status", source+" registry")
	if err != nil {
		return nil, err
	}
	sourceRecordTypes, err := stringArray(registry["source_record_types"], source+" source_record_types", true)
	if err != nil {
		return nil, err
	}
	referencePackKeys, err := stringArray(schema["required_reference_pack_keys"], source+" required_reference_pack_keys", false)
	if err != nil {
		return nil, err
	}
	technicalFields, err := stringArray(schema["technical_fields"], source+" technical_fields", false)
	if err != nil {
		return nil, err
	}
	defaultVisibleFields, err := stringArray(schema["default_visible_fields"], source+" default_visible_fields", false)
	if err != nil {
		return nil, err
	}
	defaultHiddenFields, err := stringArray(schema["default_hidden_fields"], source+" default_hidden_fields", false)
	if err != nil {
		return nil, err
	}
	sortFields, err := stringArray(schema["sort_fields"], source+" sort_fields", false)
	if err != nil {
		return nil, err
	}
	filterFields, err := stringArray(schema["filter_fields"], source+" filter_fields", false)
	if err != nil {
		return nil, err
	}
	groupingFields, err := stringArray(schema["grouping_fields"], source+" grouping_fields", false)
	if err != nil {
		return nil, err
	}
	createInputs, err := normalizeProjectionCreateInputs(schema["create_inputs"], source)
	if err != nil {
		return nil, err
	}

	fields, err := normalizeProjectionFields(schema["fields"], source)
	if err != nil {
		return nil, err
	}
	syntheticFields, syntheticKeys, err := normalizeProjectionSyntheticFields(schema["synthetic_filter_predicates"], source)
	if err != nil {
		return nil, err
	}
	filterFields = append(filterFields, syntheticKeys...)
	defaultSort, err := normalizeProjectionDefaultSort(schema["default_sort"], source)
	if err != nil {
		return nil, err
	}
	inlineCreate, err := asObject(schema["inline_create"], source+" inline_create")
	if err != nil {
		return nil, err
	}
	minimumCreateFieldSets, err := projectionStringMatrix(inlineCreate["minimum_create_field_sets"], source+" inline_create.minimum_create_field_sets")
	if err != nil {
		return nil, err
	}
	permitsZeroFieldCreate, err := requiredBool(inlineCreate, "permits_zero_field_create", source+" inline_create")
	if err != nil {
		return nil, err
	}
	inspectorConfig, err := normalizeProjectionInspectorConfig(schema["inspector_config"], source)
	if err != nil {
		return nil, err
	}
	sortNullOrder, err := requiredString(schema, "sort_null_order", source)
	if err != nil {
		return nil, err
	}

	return map[string]any{
		"createCapable":             schema["create_capable"],
		"createInputs":              createInputs,
		"defaultHiddenFields":       defaultHiddenFields,
		"defaultSort":               defaultSort,
		"defaultVisibleFields":      defaultVisibleFields,
		"fields":                    fields,
		"filterFields":              filterFields,
		"groupingFields":            groupingFields,
		"inspectorConfig":           inspectorConfig,
		"minimumCreateFieldSets":    minimumCreateFieldSets,
		"permitsZeroFieldCreate":    permitsZeroFieldCreate,
		"requiredReferencePackKeys": referencePackKeys,
		"sortFields":                sortFields,
		"sortNullOrder":             sortNullOrder,
		"sourceRecordTypes":         sourceRecordTypes,
		"surfaceKind":               surfaceKind,
		"surfaceStatus":             surfaceStatus,
		"syntheticFilterFields":     syntheticFields,
		"technicalFields":           technicalFields,
		"title":                     title,
		"viewSchemaId":              viewSchemaID,
	}, nil
}

func normalizeProjectionCreateInputs(value any, source string) ([]any, error) {
	inputs, err := objectArrayAllowEmpty(value, source+" create_inputs")
	if err != nil {
		return nil, err
	}
	result := make([]any, 0, len(inputs))
	for index, input := range inputs {
		label := fmt.Sprintf("%s create_inputs[%d]", source, index+1)
		inputKey, err := requiredString(input, "input_key", label)
		if err != nil {
			return nil, err
		}
		valueContractID, err := requiredString(input, "value_contract_id", label)
		if err != nil {
			return nil, err
		}
		result = append(result, map[string]any{
			"inputKey":        inputKey,
			"nullable":        input["nullable"],
			"required":        input["required"],
			"valueContractId": valueContractID,
		})
	}
	return result, nil
}

func normalizeProjectionFields(value any, source string) ([]any, error) {
	fields, err := objectArray(value, source+" fields")
	if err != nil {
		return nil, err
	}
	result := make([]any, 0, len(fields))
	for index, field := range fields {
		label := fmt.Sprintf("%s fields[%d]", source, index+1)
		fieldKey, err := requiredString(field, "field_key", label)
		if err != nil {
			return nil, err
		}
		fieldLabel, err := requiredString(field, "label", label)
		if err != nil {
			return nil, err
		}
		filterOps, err := stringArray(field["filter_ops"], label+" filter_ops", false)
		if err != nil {
			return nil, err
		}
		entry := map[string]any{
			"clearable":                 field["clearable"],
			"conflictResolutionClass":   field["conflict_resolution_class"],
			"createWritable":            field["writable"] == true || field["create_writable"] == true,
			"defaultHidden":             field["default_hidden"],
			"directReferenceContractId": field["direct_reference_contract_id"],
			"directScalarContractId":    field["direct_scalar_contract_id"],
			"entityBindingMode":         field["entity_binding_mode"],
			"enumValues":                field["enum_values"],
			"fieldKey":                  fieldKey,
			"filterOps":                 filterOps,
			"gridEditable":              field["grid_editable"],
			"groupable":                 field["groupable"],
			"headerSortFieldKey":        field["header_sort_field_key"],
			"label":                     fieldLabel,
			"readKind":                  field["read_kind"],
			"sortable":                  field["sortable"],
			"stringContractId":          field["string_contract_id"],
			"writeAction":               nil,
			"writeKind":                 field["write_kind"],
		}
		if writeAction, ok := field["write_action"]; ok {
			entry["writeAction"] = writeAction
		}
		result = append(result, entry)
	}
	return result, nil
}

func normalizeProjectionSyntheticFields(value any, source string) ([]any, []string, error) {
	fields, err := objectArrayAllowEmpty(value, source+" synthetic_filter_predicates")
	if err != nil {
		return nil, nil, err
	}
	result := make([]any, 0, len(fields))
	keys := make([]string, 0, len(fields))
	for index, field := range fields {
		label := fmt.Sprintf("%s synthetic_filter_predicates[%d]", source, index+1)
		fieldKey, err := requiredString(field, "field_key", label)
		if err != nil {
			return nil, nil, err
		}
		fieldLabel, err := requiredString(field, "label", label)
		if err != nil {
			return nil, nil, err
		}
		filterOps, err := stringArray(field["filter_ops"], label+" filter_ops", false)
		if err != nil {
			return nil, nil, err
		}
		keys = append(keys, fieldKey)
		result = append(result, map[string]any{
			"clearable":                 false,
			"conflictResolutionClass":   nil,
			"createWritable":            false,
			"defaultHidden":             true,
			"directReferenceContractId": nil,
			"directScalarContractId":    nil,
			"entityBindingMode":         nil,
			"enumValues":                nil,
			"fieldKey":                  fieldKey,
			"filterOps":                 filterOps,
			"gridEditable":              false,
			"groupable":                 false,
			"headerSortFieldKey":        nil,
			"label":                     fieldLabel,
			"readKind":                  "synthetic_filter",
			"sortable":                  false,
			"stringContractId":          nil,
			"writeAction":               nil,
			"writeKind":                 "read_only",
		})
	}
	return result, keys, nil
}

func normalizeProjectionDefaultSort(value any, source string) ([]any, error) {
	entries, err := objectArrayAllowEmpty(value, source+" default_sort")
	if err != nil {
		return nil, err
	}
	result := make([]any, 0, len(entries))
	for index, entry := range entries {
		label := fmt.Sprintf("%s default_sort[%d]", source, index+1)
		fieldKey, err := requiredString(entry, "field_key", label)
		if err != nil {
			return nil, err
		}
		direction, err := requiredString(entry, "direction", label)
		if err != nil {
			return nil, err
		}
		result = append(result, map[string]any{"direction": direction, "fieldKey": fieldKey})
	}
	return result, nil
}

func projectionStringMatrix(value any, label string) ([]any, error) {
	rows, ok := value.([]any)
	if !ok {
		return nil, fmt.Errorf("%s must be an array", label)
	}
	result := make([]any, 0, len(rows))
	for index, row := range rows {
		values, err := stringArray(row, fmt.Sprintf("%s[%d]", label, index+1), false)
		if err != nil {
			return nil, err
		}
		result = append(result, values)
	}
	return result, nil
}

func normalizeProjectionInspectorConfig(value any, source string) (map[string]any, error) {
	config, err := asObject(value, source+" inspector_config")
	if err != nil {
		return nil, err
	}
	panels, err := objectArray(config["panels"], source+" inspector_config.panels")
	if err != nil {
		return nil, err
	}
	normalizedPanels := make([]any, 0, len(panels))
	for index, panel := range panels {
		label := fmt.Sprintf("%s inspector_config.panels[%d]", source, index+1)
		panelID, err := requiredString(panel, "panel_id", label)
		if err != nil {
			return nil, err
		}
		panelLabel, err := requiredString(panel, "label", label)
		if err != nil {
			return nil, err
		}
		normalizedPanels = append(normalizedPanels, map[string]any{"label": panelLabel, "panelId": panelID})
	}
	groups, err := objectArrayAllowEmpty(config["feature_groups"], source+" inspector_config.feature_groups")
	if err != nil {
		return nil, err
	}
	normalizedGroups := make([]any, 0, len(groups))
	for index, group := range groups {
		label := fmt.Sprintf("%s inspector_config.feature_groups[%d]", source, index+1)
		route, err := normalizeProjectionInspectorRoute(group["route_binding"], label)
		if err != nil {
			return nil, err
		}
		seeds, err := normalizeProjectionInspectorSeeds(group["seed_bindings"], label)
		if err != nil {
			return nil, err
		}
		disabledWhen, err := stringArray(group["disabled_when"], label+" disabled_when", false)
		if err != nil {
			return nil, err
		}
		normalizedGroups = append(normalizedGroups, map[string]any{
			"disabledWhen":          disabledWhen,
			"failureResultBehavior": group["failure_result_behavior"],
			"featureGroupKey":       group["feature_group_key"],
			"label":                 group["label"],
			"minimumIncidentRole":   group["minimum_incident_role"],
			"mutates":               group["mutates"],
			"panelId":               group["panel_id"],
			"requiresConfirmation":  group["requires_confirmation"],
			"routeBinding":          route,
			"seedBindings":          seeds,
			"successResultBehavior": group["success_result_behavior"],
		})
	}
	subjectBinding, err := asObject(config["subject_binding"], source+" inspector_config.subject_binding")
	if err != nil {
		return nil, err
	}
	return map[string]any{
		"defaultOpen":                config["default_open"],
		"featureGroups":              normalizedGroups,
		"inspectorConfigSchemaId":    config["inspector_config_schema_id"],
		"noRowState":                 config["no_row_state"],
		"panels":                     normalizedPanels,
		"subjectBinding":             map[string]any{"kind": subjectBinding["kind"]},
		"unsupportedFeatureBehavior": config["unsupported_feature_behavior"],
		"viewSchemaId":               config["view_schema_id"],
	}, nil
}

func normalizeProjectionInspectorRoute(value any, label string) (map[string]any, error) {
	route, err := asObject(value, label+" route_binding")
	if err != nil {
		return nil, err
	}
	result := map[string]any{"kind": route["kind"], "owner": route["owner"]}
	if target, ok := route["target_view_schema_id"]; ok {
		result["targetViewSchemaId"] = target
	}
	if action, ok := route["action_key"]; ok {
		result["actionKey"] = action
	}
	return result, nil
}

func normalizeProjectionInspectorSeeds(value any, label string) ([]any, error) {
	seeds, err := objectArrayAllowEmpty(value, label+" seed_bindings")
	if err != nil {
		return nil, err
	}
	result := make([]any, 0, len(seeds))
	for index, seed := range seeds {
		seedLabel := fmt.Sprintf("%s seed_bindings[%d]", label, index+1)
		source, err := asObject(seed["source"], seedLabel+" source")
		if err != nil {
			return nil, err
		}
		normalizedSource := map[string]any{"kind": source["kind"]}
		if fieldKey, ok := source["source_field_key"]; ok {
			normalizedSource["sourceFieldKey"] = fieldKey
		}
		if constant, ok := source["value"]; ok {
			normalizedSource["value"] = constant
		}
		result = append(result, map[string]any{
			"source":         normalizedSource,
			"targetFieldKey": seed["target_field_key"],
		})
	}
	return result, nil
}
