package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	vendorRoot = "tools/networkflow-unicode17/vendor/norm"
	outputRoot = "internal/gen/networkflowunicode"
)

var sourceFiles = []string{
	"composition.go",
	"forminfo.go",
	"input.go",
	"iter.go",
	"normalize.go",
	"readwriter.go",
	"tables17.0.0.go",
	"transform.go",
	"trie.go",
}

type provenance struct {
	SchemaID       string            `json:"schema_id"`
	UpstreamModule string            `json:"upstream_module"`
	UpstreamTag    string            `json:"upstream_tag"`
	UnicodeVersion string            `json:"unicode_version"`
	Files          map[string]string `json:"files_sha256"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "generate Network Flow Unicode 17 NFC:", err)
		os.Exit(1)
	}
}

func run() error {
	raw, err := os.ReadFile("contracts/network-flow/unicode17-nfc.provenance.json")
	if err != nil {
		return err
	}
	var owner provenance
	if err := json.Unmarshal(raw, &owner); err != nil {
		return err
	}
	if owner.SchemaID != "cartulary.network_flow_unicode17_nfc_provenance.v1" || owner.UpstreamModule != "golang.org/x/text" || owner.UpstreamTag != "v0.37.0" || owner.UnicodeVersion != "17.0.0" {
		return fmt.Errorf("unexpected Unicode provenance header")
	}
	if len(owner.Files) != len(sourceFiles) {
		return fmt.Errorf("provenance file count %d, want %d", len(owner.Files), len(sourceFiles))
	}
	if err := os.RemoveAll(outputRoot); err != nil {
		return err
	}
	if err := os.MkdirAll(outputRoot, 0o755); err != nil {
		return err
	}
	sort.Strings(sourceFiles)
	for _, name := range sourceFiles {
		input, err := os.ReadFile(filepath.Join(vendorRoot, name))
		if err != nil {
			return err
		}
		digest := sha256.Sum256(input)
		if hex.EncodeToString(digest[:]) != owner.Files[name] {
			return fmt.Errorf("%s does not match immutable provenance", name)
		}
		input = stripBuildConstraint(input)
		input = bytes.Replace(input, []byte(`package norm // import "golang.org/x/text/unicode/norm"`), []byte("package networkflowunicode"), 1)
		input = bytes.Replace(input, []byte("package norm"), []byte("package networkflowunicode"), 1)
		generated := append([]byte("// Code generated by tools/networkflow-unicode17 from golang.org/x/text v0.37.0; DO NOT EDIT.\n\n"), input...)
		formatted, err := format.Source(generated)
		if err != nil {
			return fmt.Errorf("format %s: %w", name, err)
		}
		if err := os.WriteFile(filepath.Join(outputRoot, name), formatted, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func stripBuildConstraint(input []byte) []byte {
	lines := strings.Split(string(input), "\n")
	out := lines[:0]
	for _, line := range lines {
		if strings.HasPrefix(line, "//go:build ") {
			continue
		}
		out = append(out, line)
	}
	return []byte(strings.Join(out, "\n"))
}
