import { readFileSync } from "node:fs";
import path from "node:path";

const metadataKeys = new Set([
  "version",
  "name",
  "document_class",
  "status",
  "design_contract_schema_id",
  "token_registry_schema_id",
  "default_theme_id",
  "description",
]);

export const tokenNamespaces = [
  "colors",
  "typography",
  "spacing",
  "density",
  "rounded",
  "border",
  "elevation",
  "motion",
  "layout",
  "components",
];

const namespaceSet = new Set(tokenNamespaces);
const tokenRefPattern = /\{([A-Za-z][A-Za-z0-9-]*)\.([^{}]+)\}/g;

export class DesignTokenValidationError extends Error {
  constructor(failures) {
    super(
      `design token validation failed: ${failures
        .map((failure) => `${failure.class}: ${failure.message}`)
        .join("; ")}`,
    );
    this.name = "DesignTokenValidationError";
    this.failures = failures;
  }
}

export function loadDesignTokenDocument(filePath) {
  return parseDesignTokenDocument(readFileSync(filePath, "utf8"), {
    sourcePath: path.normalize(filePath),
  });
}

export function parseDesignTokenDocument(content, { sourcePath = "docs/design.md" } = {}) {
  const failures = [];
  const frontMatter = extractFrontMatter(content, failures, sourcePath);
  const parsed = frontMatter === null ? null : parseYamlSubset(frontMatter, failures);

  if (parsed !== null) {
    validateFrontMatter(parsed, failures);
  }

  if (failures.length > 0 || parsed === null) {
    throw new DesignTokenValidationError(failures);
  }

  const registry = {};
  for (const namespace of tokenNamespaces) {
    registry[namespace] = parsed[namespace];
  }

  const tokenMap = flattenRegistry(registry);
  validateReferences(parsed.description, tokenMap, failures, "description");
  for (const [tokenPath, value] of tokenMap.entries()) {
    validateReferences(value.raw, tokenMap, failures, tokenPath);
  }

  if (failures.length === 0) {
    validateRegistryValues(registry, tokenMap, failures);
    validateBodyTokenReferences(frontMatter.body, tokenMap, failures);
  }

  if (failures.length > 0) {
    throw new DesignTokenValidationError(failures);
  }

  const resolvedTokenMap = resolveAllTokens(tokenMap, failures);
  if (failures.length > 0) {
    throw new DesignTokenValidationError(failures);
  }

  const tokenVars = buildTokenVars(resolvedTokenMap);
  return {
    metadata: {
      defaultThemeId: parsed.default_theme_id,
      designContractSchemaId: parsed.design_contract_schema_id,
      documentClass: parsed.document_class,
      name: parsed.name,
      status: parsed.status,
      tokenRegistrySchemaId: parsed.token_registry_schema_id,
      version: parsed.version,
    },
    registry,
    tokenMap,
    tokenVars,
  };
}

export function renderDesignTokenTypeScript(document) {
  const tokenVarEntries = [...document.tokenVars.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );
  const cssText = renderCssText(document.metadata.defaultThemeId, tokenVarEntries);
  const tokenVarObject = Object.fromEntries(tokenVarEntries);

  return [
    "// Code generated by scripts/generate-design-tokens.mjs; DO NOT EDIT.",
    "",
    `export const cartularyDefaultThemeId = ${JSON.stringify(document.metadata.defaultThemeId)} as const;`,
    "",
    `export const cartularyDesignTokenVars = ${stableJSONStringify(tokenVarObject)} as const;`,
    "",
    `export const cartularyDesignThemeCssText = ${JSON.stringify(cssText)} as const;`,
    "",
    "export type CartularyDesignTokenVarName = keyof typeof cartularyDesignTokenVars;",
    "export type CartularyDefaultThemeId = typeof cartularyDefaultThemeId;",
    "",
  ].join("\n");
}

function extractFrontMatter(content, failures, sourcePath) {
  if (!content.startsWith("---\n")) {
    failures.push({
      class: "invalid_frontmatter_schema",
      message: `${sourcePath}: missing opening YAML front matter delimiter`,
    });
    return null;
  }
  const end = content.indexOf("\n---\n", 4);
  if (end < 0) {
    failures.push({
      class: "invalid_frontmatter_schema",
      message: `${sourcePath}: missing closing YAML front matter delimiter`,
    });
    return null;
  }
  return {
    body: content.slice(end + "\n---\n".length),
    yaml: content.slice(4, end),
  };
}

function parseYamlSubset(frontMatter, failures) {
  const root = {};
  const stack = [{ indent: -1, object: root, path: "" }];
  const lines = frontMatter.yaml.split(/\r?\n/);

  for (const [lineIndex, line] of lines.entries()) {
    if (line.trim() === "" || line.trimStart().startsWith("#")) {
      continue;
    }
    const match = /^(\s*)([^:\s][^:]*):(.*)$/.exec(line);
    if (!match) {
      failures.push({
        class: "invalid_frontmatter_schema",
        message: `line ${lineIndex + 1}: unsupported YAML front matter syntax`,
      });
      continue;
    }
    const indent = match[1].length;
    const key = match[2].trim();
    const rawValue = match[3];
    if (indent % 2 !== 0) {
      failures.push({
        class: "invalid_frontmatter_schema",
        message: `line ${lineIndex + 1}: indentation must use two-space steps`,
      });
      continue;
    }
    while (stack.length > 0 && indent <= stack[stack.length - 1].indent) {
      stack.pop();
    }
    const parent = stack[stack.length - 1];
    if (parent === undefined) {
      failures.push({
        class: "invalid_frontmatter_schema",
        message: `line ${lineIndex + 1}: invalid indentation`,
      });
      continue;
    }
    if (Object.hasOwn(parent.object, key)) {
      const fullPath = parent.path === "" ? key : `${parent.path}.${key}`;
      failures.push({
        class: "duplicate_frontmatter_key",
        message: `duplicate key ${fullPath}`,
      });
      continue;
    }
    const trimmedValue = rawValue.trim();
    if (trimmedValue === "") {
      const next = {};
      parent.object[key] = next;
      stack.push({
        indent,
        object: next,
        path: parent.path === "" ? key : `${parent.path}.${key}`,
      });
      continue;
    }
    parent.object[key] = parseScalar(trimmedValue, failures, lineIndex + 1);
  }

  return failures.length > 0 ? null : root;
}

function parseScalar(value, failures, lineNumber) {
  if (value.startsWith('"') && value.endsWith('"')) {
    try {
      return JSON.parse(value);
    } catch {
      failures.push({
        class: "invalid_frontmatter_schema",
        message: `line ${lineNumber}: invalid quoted string`,
      });
      return "";
    }
  }
  if (/^-?\d+$/.test(value)) {
    return Number.parseInt(value, 10);
  }
  if (/^-?\d+\.\d+$/.test(value)) {
    return Number.parseFloat(value);
  }
  return value;
}

function validateFrontMatter(parsed, failures) {
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    failures.push({
      class: "invalid_frontmatter_schema",
      message: "front matter must be a mapping",
    });
    return;
  }
  for (const key of Object.keys(parsed)) {
    if (!metadataKeys.has(key) && !namespaceSet.has(key)) {
      failures.push({
        class: "unknown_token_namespace",
        message: `unknown top-level front matter key ${key}`,
      });
    }
  }
  const expectedMetadata = {
    default_theme_id: "dark_graphite",
    design_contract_schema_id: "cartulary.design_direction.v1",
    document_class: "design-direction-contract",
    token_registry_schema_id: "cartulary.design_tokens.v1",
  };
  for (const [key, expected] of Object.entries(expectedMetadata)) {
    if (parsed[key] !== expected) {
      failures.push({
        class: "invalid_frontmatter_schema",
        message: `${key} must equal ${expected}`,
      });
    }
  }
  for (const key of ["version", "name", "status"]) {
    if (typeof parsed[key] !== "string" || parsed[key].trim() === "") {
      failures.push({
        class: "invalid_frontmatter_schema",
        message: `${key} must be a non-empty string`,
      });
    }
  }
  for (const namespace of tokenNamespaces) {
    if (!isPlainObject(parsed[namespace])) {
      failures.push({
        class: "invalid_frontmatter_schema",
        message: `${namespace} must be a mapping`,
      });
    }
  }
}

function flattenRegistry(registry) {
  const tokenMap = new Map();
  const visit = (namespace, value, pathParts) => {
    if (pathParts.length > 0) {
      const tokenPath = `${namespace}.${pathParts.join(".")}`;
      tokenMap.set(tokenPath, {
        namespace,
        raw: value,
        tokenKey: pathParts.join("."),
      });
    }
    if (isPlainObject(value)) {
      for (const key of Object.keys(value)) {
        visit(namespace, value[key], [...pathParts, key]);
      }
      return;
    }
  };
  for (const namespace of tokenNamespaces) {
    visit(namespace, registry[namespace], []);
  }
  return tokenMap;
}

function validateReferences(value, tokenMap, failures, context) {
  if (typeof value !== "string") {
    return;
  }
  for (const ref of tokenRefsIn(value)) {
    if (!namespaceSet.has(ref.namespace)) {
      failures.push({
        class: "unknown_token_namespace",
        message: `${context} references unknown namespace ${ref.namespace}`,
      });
      continue;
    }
    if (!tokenMap.has(ref.path)) {
      failures.push({
        class: "unknown_token_key",
        message: `${context} references unknown token ${ref.path}`,
      });
    }
  }
}

function validateBodyTokenReferences(body, tokenMap, failures) {
  const bodyWithoutFences = body.replace(/```[\s\S]*?```/g, "");
  for (const ref of tokenRefsIn(bodyWithoutFences)) {
    if (ref.namespace === "namespace" || ref.tokenKey.includes("*")) {
      continue;
    }
    if (!namespaceSet.has(ref.namespace)) {
      failures.push({
        class: "unknown_token_namespace",
        message: `body references unknown namespace ${ref.namespace}`,
      });
      continue;
    }
    if (!tokenMap.has(ref.path)) {
      failures.push({
        class: "invalid_body_token_usage",
        message: `body references unknown token ${ref.path}`,
      });
    }
  }
}

function tokenRefsIn(value) {
  const refs = [];
  tokenRefPattern.lastIndex = 0;
  let match;
  while ((match = tokenRefPattern.exec(value)) !== null) {
    refs.push({
      namespace: match[1],
      path: `${match[1]}.${match[2]}`,
      text: match[0],
      tokenKey: match[2],
    });
  }
  return refs;
}

function resolveAllTokens(tokenMap, failures) {
  const resolved = new Map();
  const resolvePath = (tokenPath, stack) => {
    if (resolved.has(tokenPath)) {
      return resolved.get(tokenPath).resolved;
    }
    if (stack.includes(tokenPath)) {
      failures.push({
        class: "token_reference_cycle",
        message: `token reference cycle: ${[...stack, tokenPath].join(" -> ")}`,
      });
      return "";
    }
    const entry = tokenMap.get(tokenPath);
    if (entry === undefined) {
      failures.push({
        class: "unknown_token_key",
        message: `unknown token ${tokenPath}`,
      });
      return "";
    }
    const value = resolveValue(entry.raw, [...stack, tokenPath]);
    resolved.set(tokenPath, {
      ...entry,
      resolved: value,
    });
    return value;
  };

  const resolveValue = (value, stack) => {
    if (typeof value !== "string") {
      return value;
    }
    const exact = exactTokenRef(value);
    if (exact !== null) {
      return resolvePath(exact.path, stack);
    }
    let output = value;
    for (const ref of tokenRefsIn(value)) {
      output = output.replace(ref.text, String(resolvePath(ref.path, stack)));
    }
    return output;
  };

  for (const tokenPath of tokenMap.keys()) {
    resolvePath(tokenPath, []);
  }
  return resolved;
}

function exactTokenRef(value) {
  const refs = tokenRefsIn(value);
  return refs.length === 1 && refs[0].text === value ? refs[0] : null;
}

function validateRegistryValues(registry, tokenMap, failures) {
  validateColorTokens(registry.colors, failures);
  validateTypographyTokens(registry.typography, failures);
  validateFlatScalarNamespace("spacing", registry.spacing, isCssPxLength, failures);
  validateDensityTokens(registry.density, failures);
  validateFlatScalarNamespace("rounded", registry.rounded, isCssPxLength, failures);
  validateFlatScalarNamespace("border", registry.border, isBorderShorthand, failures);
  validateFlatScalarNamespace("elevation", registry.elevation, isElevation, failures);
  validateFlatScalarNamespace("motion", registry.motion, isMotionValue, failures);
  validateFlatScalarNamespace("layout", registry.layout, isLayoutValue, failures);
  validateComponentTokens(registry.components, failures);

  for (const [tokenPath, entry] of tokenMap.entries()) {
    validateReferences(entry.raw, tokenMap, failures, tokenPath);
  }
}

function validateColorTokens(colors, failures) {
  for (const [key, value] of Object.entries(colors)) {
    if (typeof value === "string" && (isHexColor(value) || isRgbaColor(value) || exactTokenRef(value) !== null)) {
      continue;
    }
    failures.push({
      class: "invalid_token_value",
      message: `colors.${key} must be a hex color, rgba color, or token reference`,
    });
  }
}

function validateTypographyTokens(typography, failures) {
  const required = new Set(["fontFamily", "fontSize", "fontWeight", "lineHeight", "letterSpacing"]);
  for (const [key, value] of Object.entries(typography)) {
    if (!isPlainObject(value)) {
      failures.push({
        class: "invalid_token_value",
        message: `typography.${key} must be a mapping`,
      });
      continue;
    }
    for (const property of Object.keys(value)) {
      if (!required.has(property)) {
        failures.push({
          class: "invalid_token_value",
          message: `typography.${key}.${property} is not a supported typography property`,
        });
      }
    }
    for (const property of required) {
      if (!Object.hasOwn(value, property)) {
        failures.push({
          class: "invalid_token_value",
          message: `typography.${key}.${property} is required`,
        });
      }
    }
    if (typeof value.fontFamily !== "string" || value.fontFamily.trim() === "") {
      failures.push({ class: "invalid_token_value", message: `typography.${key}.fontFamily is invalid` });
    }
    if (!isCssPxLength(value.fontSize)) {
      failures.push({ class: "invalid_token_value", message: `typography.${key}.fontSize is invalid` });
    }
    if (!Number.isInteger(value.fontWeight) || value.fontWeight < 1 || value.fontWeight > 1000) {
      failures.push({ class: "invalid_token_value", message: `typography.${key}.fontWeight is invalid` });
    }
    if (!(typeof value.lineHeight === "number" && value.lineHeight > 0) && !isCssPxLength(value.lineHeight)) {
      failures.push({ class: "invalid_token_value", message: `typography.${key}.lineHeight is invalid` });
    }
    if (!(value.letterSpacing === 0 || isCssPxLength(value.letterSpacing))) {
      failures.push({ class: "invalid_token_value", message: `typography.${key}.letterSpacing is invalid` });
    }
  }
}

function validateFlatScalarNamespace(namespace, values, validator, failures) {
  for (const [key, value] of Object.entries(values)) {
    if (!validator(value)) {
      failures.push({
        class: "invalid_token_value",
        message: `${namespace}.${key} has invalid token value ${JSON.stringify(value)}`,
      });
    }
  }
}

function validateDensityTokens(density, failures) {
  const modes = new Set(["compact", "default", "comfortable"]);
  for (const key of Object.keys(density)) {
    if (key === "default-mode") {
      continue;
    }
    if (!modes.has(key)) {
      failures.push({ class: "invalid_token_value", message: `density.${key} is not a supported mode` });
      continue;
    }
    const value = density[key];
    if (!isPlainObject(value) || !isCssPxLength(value.rowHeight) || !isCssPadding2d(value.cellPadding)) {
      failures.push({ class: "invalid_token_value", message: `density.${key} must declare rowHeight and cellPadding` });
    }
  }
  if (!modes.has(density["default-mode"])) {
    failures.push({
      class: "invalid_token_value",
      message: "density.default-mode must name compact, default, or comfortable",
    });
  }
}

function validateComponentTokens(components, failures) {
  for (const [componentKey, componentValue] of Object.entries(components)) {
    if (!isPlainObject(componentValue)) {
      failures.push({
        class: "invalid_token_value",
        message: `components.${componentKey} must be a mapping`,
      });
      continue;
    }
    for (const [propertyKey, propertyValue] of Object.entries(componentValue)) {
      if (
        typeof propertyValue === "string" &&
        (exactTokenRef(propertyValue) !== null ||
          isCssPxLength(propertyValue) ||
          isCssPadding2d(propertyValue) ||
          isBorderShorthand(propertyValue) ||
          propertyValue === "transparent")
      ) {
        continue;
      }
      if (typeof propertyValue === "number" && propertyValue >= 0) {
        continue;
      }
      failures.push({
        class: "invalid_token_value",
        message: `components.${componentKey}.${propertyKey} has invalid token value ${JSON.stringify(propertyValue)}`,
      });
    }
  }
}

function isPlainObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function isHexColor(value) {
  return typeof value === "string" && /^#[0-9A-F]{6}$/.test(value);
}

function isRgbaColor(value) {
  if (typeof value !== "string") {
    return false;
  }
  const match = /^rgba\((\d{1,3}), (\d{1,3}), (\d{1,3}), (0|1|0?\.\d+)\)$/.exec(value);
  if (!match) {
    return false;
  }
  const channels = match.slice(1, 4).map((part) => Number.parseInt(part, 10));
  const alpha = Number.parseFloat(match[4]);
  return channels.every((channel) => channel >= 0 && channel <= 255) && alpha >= 0 && alpha <= 1;
}

function isCssPxLength(value) {
  if (typeof value !== "string") {
    return false;
  }
  const match = /^(\d+(?:\.\d+)?)px$/.exec(value);
  if (!match) {
    return false;
  }
  const number = Number.parseFloat(match[1]);
  return number >= 0 && number <= 9999;
}

function isCssPadding2d(value) {
  return typeof value === "string" && /^(\d+(?:\.\d+)?)px (\d+(?:\.\d+)?)px$/.test(value);
}

function isCssPercent(value) {
  if (typeof value !== "string") {
    return false;
  }
  const match = /^(\d+)%$/.exec(value);
  if (!match) {
    return false;
  }
  const number = Number.parseInt(match[1], 10);
  return number >= 0 && number <= 100;
}

function isCssDuration(value) {
  if (typeof value !== "string") {
    return false;
  }
  const match = /^(\d+)ms$/.exec(value);
  if (!match) {
    return false;
  }
  const number = Number.parseInt(match[1], 10);
  return number >= 0 && number <= 60000;
}

function isCubicBezier(value) {
  return typeof value === "string" && /^cubic-bezier\((0(?:\.\d+)?|1(?:\.0+)?), -?\d+(?:\.\d+)?, (0(?:\.\d+)?|1(?:\.0+)?), -?\d+(?:\.\d+)?\)$/.test(value);
}

function isBorderShorthand(value) {
  return typeof value === "string" && /^\d+(?:\.\d+)?px (solid|dashed|dotted) \{colors\.[^{}]+\}$/.test(value);
}

function isElevation(value) {
  return (
    value === "none" ||
    (typeof value === "string" &&
      /^-?(?:0|\d+(?:\.\d+)?px) -?(?:0|\d+(?:\.\d+)?px) (?:0|\d+(?:\.\d+)?px) rgba\(\d{1,3}, \d{1,3}, \d{1,3}, (0|1|0?\.\d+)\)$/.test(value))
  );
}

function isMotionValue(value) {
  return isCssDuration(value) || isCubicBezier(value);
}

function isLayoutValue(value) {
  return (
    isCssPxLength(value) ||
    isCssPercent(value) ||
    (typeof value === "string" && /^\d+x\d+ CSS px$/.test(value)) ||
    (typeof value === "string" && /^min\(\d+(?:\.\d+)?px, \d+vw\)$/.test(value))
  );
}

function buildTokenVars(resolvedTokenMap) {
  const vars = new Map();
  for (const [tokenPath, entry] of resolvedTokenMap.entries()) {
    if (isPlainObject(entry.resolved)) {
      continue;
    }
    const variableName =
      entry.namespace === "components"
        ? componentVariableName(entry.tokenKey)
        : primitiveVariableName(entry.namespace, entry.tokenKey);
    vars.set(variableName, String(entry.resolved));
  }
  return vars;
}

function primitiveVariableName(namespace, tokenKey) {
  return `--ct-${namespace}-${tokenKey.replaceAll(".", "-")}`;
}

function componentVariableName(tokenKey) {
  const parts = tokenKey.split(".");
  return `--ct-component-${parts.join("-")}`;
}

function renderCssText(themeId, tokenVarEntries) {
  const declarations = tokenVarEntries.map(([name, value]) => `  ${name}: ${value};`);
  return [`:root,`, `[data-cartulary-theme="${themeId}"] {`, ...declarations, `}`].join("\n");
}

function stableJSONStringify(value) {
  return JSON.stringify(value, Object.keys(value).sort(), 2);
}
