#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(unset CDPATH && cd -- "$(dirname "$0")/.." && pwd)"
CHECKER="$ROOT_DIR/tools/harness/generated-artifacts/check-generated-artifact-policy.mjs"
VET_WRAPPER="$ROOT_DIR/tools/harness/static-analysis/go-vet.sh"
cleanup_paths=()

# shellcheck source=tools/harness/test-support/harness-scratch.sh
# shellcheck disable=SC1091
source "$ROOT_DIR/tools/harness/test-support/harness-scratch.sh"

cleanup() {
  local path
  for path in "${cleanup_paths[@]}"; do
    rm -rf "$path"
  done
}

trap cleanup EXIT

fail() {
  echo "$*" >&2
  exit 1
}

assert_contains() {
  local haystack="$1"
  local needle="$2"
  local label="$3"

  if [[ "$haystack" != *"$needle"* ]]; then
    fail "$label: expected output to contain [$needle]"
  fi
}

assert_not_contains() {
  local haystack="$1"
  local needle="$2"
  local label="$3"

  if [[ "$haystack" == *"$needle"* ]]; then
    fail "$label: expected output not to contain [$needle]"
  fi
}

write_policy() {
  local repo="$1"
  cat >"$repo/tools/generated_artifact_policy.json" <<'JSON'
{
  "schema_id": "cartulary.generated_artifact_policy.v1",
  "ignored_sentinel_filenames": [".gitkeep"],
  "generated_roots": [
    {
      "path": "internal/gen",
      "allowed_extensions": [".go"],
      "required_marker": "^// Code generated .* DO NOT EDIT\\.$"
    },
    {
      "path": "packages/protocol-ts/src/generated",
      "allowed_extensions": [".ts"],
      "required_marker": "^// Code generated .* DO NOT EDIT\\.$"
    },
    {
      "path": "packages/ui-contracts/src/generated",
      "allowed_extensions": [".ts"],
      "required_marker": "^// Code generated .* DO NOT EDIT\\.$"
    }
  ],
  "generated_files": [
    {
      "path": "tools/task_surface.generated.mk",
      "allowed_extensions": [".mk"],
      "required_marker": "^# Code generated .* DO NOT EDIT\\.$"
    }
  ],
  "lint_scope_checks": {
    "shell_sources": [
      {
        "path": "tools/harness/static-analysis/go-format.sh",
        "must_contain": ["tools/harness/generated-artifacts/generated-artifacts.sh", "cartulary_is_authored_go_file"]
      },
      {
        "path": "tools/harness/static-analysis/go-vet.sh",
        "must_contain": ["tools/harness/generated-artifacts/generated-artifacts.sh", "cartulary_filter_authored_go_packages"]
      },
      {
        "path": "tools/harness/static-analysis/go-staticcheck.sh",
        "must_contain": ["tools/harness/generated-artifacts/generated-artifacts.sh", "cartulary_filter_authored_go_packages"]
      },
      {
        "path": "tools/harness/static-analysis/go-govulncheck.sh",
        "must_contain": ["tools/harness/generated-artifacts/generated-artifacts.sh", "cartulary_filter_authored_go_packages"]
      },
      {
        "path": "tools/harness/static-analysis/shellcheck.sh",
        "must_contain": ["tools/harness/generated-artifacts/generated-artifacts.sh", "cartulary_is_generated_artifact_path"],
        "must_not_contain": ["*/generated/*", "generated/*"]
      }
    ],
    "biome": {
      "path": "biome.json",
      "required_files_includes": [
        "!packages/protocol-ts/src/generated/**",
        "!packages/ui-contracts/src/generated/**"
      ],
      "forbidden_files_includes": [
        "!packages/protocol-ts/src/generated",
        "!packages/ui-contracts/src/generated"
      ],
      "required_override_includes": [
        "!packages/protocol-ts/src/generated/**",
        "!packages/ui-contracts/src/generated/**"
      ]
    },
    "frontend_import_boundaries": {
      "path": "tools/frontend_import_boundaries.json",
      "required_scan_excludes": [
        "packages/protocol-ts/src/generated/**",
        "packages/ui-contracts/src/generated/**"
      ],
      "required_restricted_paths": [
        "packages/protocol-ts/src/generated",
        "packages/ui-contracts/src/generated"
      ]
    },
    "markdownlint": {
      "path": ".markdownlint-cli2.jsonc",
      "required_globs": [
        "*.md",
        "docs/*.md"
      ],
      "required_ignores": [
        "docs/testing/phase*_coverage_ledger.md",
        "docs/testing/frontend_phase_coverage_ledgers/*_coverage_ledger.md",
        "internal/gen/**",
        "packages/protocol-ts/src/generated/**",
        "packages/ui-contracts/src/generated/**"
      ],
      "forbidden_globs": [
        "docs/testing/**/*.md",
        "internal/gen/**/*.md",
        "packages/protocol-ts/src/generated/**/*.md",
        "packages/ui-contracts/src/generated/**/*.md"
      ],
      "required_rules": [
        "MD001",
        "MD040",
        "MD056"
      ],
      "disabled_rules": [
        "MD013"
      ]
    }
  }
}
JSON
}

write_support_files() {
  local repo="$1"
  mkdir -p \
    "$repo/internal/gen/contracts" \
    "$repo/packages/protocol-ts/src/generated" \
    "$repo/packages/ui-contracts/src/generated" \
    "$repo/tools/harness/generated-artifacts" \
    "$repo/tools/harness/static-analysis"

  printf '%s\n' '// Code generated by test; DO NOT EDIT.' 'package contracts' >"$repo/internal/gen/contracts/contracts_gen.go"
  printf '%s\n' '// Code generated by test; DO NOT EDIT.' 'export const value = 1;' >"$repo/packages/protocol-ts/src/generated/contracts.ts"
  printf '%s\n' '// Code generated by test; DO NOT EDIT.' 'export const designTokens = {};' >"$repo/packages/ui-contracts/src/generated/design-tokens.ts"
  printf '%s\n' '# Code generated by test; DO NOT EDIT.' '.PHONY: help' >"$repo/tools/task_surface.generated.mk"
  : >"$repo/internal/gen/contracts/.gitkeep"
  : >"$repo/packages/protocol-ts/src/generated/.gitkeep"
  : >"$repo/packages/ui-contracts/src/generated/.gitkeep"
  cat >"$repo/tools/harness/generated-artifacts/generated-artifacts.sh" <<'EOF'
cartulary_is_authored_go_file() { :; }
cartulary_filter_authored_go_packages() { :; }
cartulary_is_generated_artifact_path() { :; }
EOF
  cat >"$repo/tools/harness/static-analysis/go-format.sh" <<'EOF'
source tools/harness/generated-artifacts/generated-artifacts.sh
cartulary_is_authored_go_file
EOF
  cat >"$repo/tools/harness/static-analysis/go-vet.sh" <<'EOF'
source tools/harness/generated-artifacts/generated-artifacts.sh
cartulary_filter_authored_go_packages
EOF
  cat >"$repo/tools/harness/static-analysis/go-staticcheck.sh" <<'EOF'
source tools/harness/generated-artifacts/generated-artifacts.sh
cartulary_filter_authored_go_packages
EOF
  cat >"$repo/tools/harness/static-analysis/go-govulncheck.sh" <<'EOF'
source tools/harness/generated-artifacts/generated-artifacts.sh
cartulary_filter_authored_go_packages
EOF
  cat >"$repo/tools/harness/static-analysis/shellcheck.sh" <<'EOF'
source tools/harness/generated-artifacts/generated-artifacts.sh
cartulary_is_generated_artifact_path
EOF
  cat >"$repo/biome.json" <<'JSON'
{
  "files": {
    "includes": [
      "packages/protocol-ts/src/**",
      "!packages/protocol-ts/src/generated/**",
      "packages/ui-contracts/src/**",
      "!packages/ui-contracts/src/generated/**"
    ]
  },
  "overrides": [
    {
      "includes": [
        "packages/protocol-ts/src/**",
        "!packages/protocol-ts/src/generated/**",
        "packages/ui-contracts/src/**",
        "!packages/ui-contracts/src/generated/**"
      ]
    }
  ]
}
JSON
  cat >"$repo/tools/frontend_import_boundaries.json" <<'JSON'
{
  "schema_id": "cartulary.frontend_import_boundaries.v2",
  "scan_excludes": [
    "packages/protocol-ts/src/generated/**",
    "packages/ui-contracts/src/generated/**"
  ],
  "rules": [
    {
      "id": "frontend-generated-protocol-boundary",
      "restricted_imports": [
        {
          "kind": "path_prefix",
          "path": "packages/protocol-ts/src/generated"
        }
      ]
    },
    {
      "id": "frontend-generated-design-token-boundary",
      "restricted_imports": [
        {
          "kind": "path_prefix",
          "path": "packages/ui-contracts/src/generated"
        }
      ]
    }
  ]
}
JSON
  cat >"$repo/.markdownlint-cli2.jsonc" <<'JSON'
{
  "fix": false,
  "gitignore": true,
  "globs": [
    "*.md",
    "docs/*.md"
  ],
  "ignores": [
    "docs/testing/phase*_coverage_ledger.md",
    "docs/testing/frontend_phase_coverage_ledgers/*_coverage_ledger.md",
    "internal/gen/**",
    "packages/protocol-ts/src/generated/**",
    "packages/ui-contracts/src/generated/**"
  ],
  "config": {
    "default": false,
    "MD001": true,
    "MD013": false,
    "MD040": true,
    "MD056": true
  }
}
JSON
}

make_policy_repo() {
  local repo
  repo="$(cartulary_harness_mktemp_dir generated-policy.XXXXXX)"
  cleanup_paths+=("$repo")
  git -C "$repo" init -q
  write_support_files "$repo"
  write_policy "$repo"
  git -C "$repo" add -A
  printf '%s\n' "$repo"
}

run_policy() {
  local repo="$1"
  node "$CHECKER" --root "$repo" --policy tools/generated_artifact_policy.json
}

expect_policy_failure() {
  local repo="$1"
  local expected="$2"
  local label="$3"
  local output
  local status

  set +e
  output="$(run_policy "$repo" 2>&1)"
  status=$?
  set -e
  if [[ "$status" -eq 0 ]]; then
    fail "$label: expected generated artifact policy failure"
  fi
  assert_contains "$output" "$expected" "$label"
}

valid_repo="$(make_policy_repo)"
run_policy "$valid_repo" >/dev/null

missing_marker_repo="$(make_policy_repo)"
printf '%s\n' 'package contracts' >"$missing_marker_repo/internal/gen/contracts/contracts_gen.go"
expect_policy_failure "$missing_marker_repo" "internal/gen/contracts/contracts_gen.go: missing required generated marker" "missing generated marker"

untracked_repo="$(make_policy_repo)"
printf '%s\n' 'package contracts' >"$untracked_repo/internal/gen/contracts/untracked.go"
expect_policy_failure "$untracked_repo" "internal/gen/contracts/untracked.go: missing required generated marker" "untracked generated file marker"

unsupported_repo="$(make_policy_repo)"
printf '%s\n' 'generated text' >"$unsupported_repo/internal/gen/contracts/readme.txt"
expect_policy_failure "$unsupported_repo" "internal/gen/contracts/readme.txt: unsupported generated extension .txt" "unsupported generated extension"

make_marker_repo="$(make_policy_repo)"
printf '%s\n' '.PHONY: help' >"$make_marker_repo/tools/task_surface.generated.mk"
expect_policy_failure "$make_marker_repo" "tools/task_surface.generated.mk: missing required generated marker" "generated Make marker"

biome_repo="$(make_policy_repo)"
cat >"$biome_repo/biome.json" <<'JSON'
{
  "files": {
    "includes": [
      "packages/protocol-ts/src/**",
      "!packages/protocol-ts/src/generated"
    ]
  },
  "overrides": [
    {
      "includes": ["packages/protocol-ts/src/**"]
    }
  ]
}
JSON
expect_policy_failure "$biome_repo" "biome.json: files.includes must exclude !packages/protocol-ts/src/generated/**" "Biome recursive generated exclusion"

shell_scope_repo="$(make_policy_repo)"
cat >"$shell_scope_repo/tools/harness/static-analysis/shellcheck.sh" <<'EOF'
source tools/harness/generated-artifacts/generated-artifacts.sh
cartulary_is_generated_artifact_path
case "$1" in
  */generated/*) exit 0 ;;
esac
EOF
expect_policy_failure "$shell_scope_repo" "tools/harness/static-analysis/shellcheck.sh: forbidden broad generated exclusion \"*/generated/*\"" "ShellCheck broad generated exclusion"

go_scope_repo="$(make_policy_repo)"
cat >"$go_scope_repo/tools/harness/static-analysis/go-vet.sh" <<'EOF'
source tools/harness/generated-artifacts/generated-artifacts.sh
go list ./internal/...
EOF
expect_policy_failure "$go_scope_repo" "tools/harness/static-analysis/go-vet.sh: missing lint scope guard \"cartulary_filter_authored_go_packages\"" "go vet generated package filter"

markdown_generated_repo="$(make_policy_repo)"
node - "$markdown_generated_repo/.markdownlint-cli2.jsonc" <<'NODE'
const fs = require("node:fs");
const file = process.argv[2];
const config = JSON.parse(fs.readFileSync(file, "utf8"));
config.ignores = config.ignores.filter((entry) => entry !== "docs/testing/phase*_coverage_ledger.md");
fs.writeFileSync(file, `${JSON.stringify(config, null, 2)}\n`);
NODE
expect_policy_failure "$markdown_generated_repo" ".markdownlint-cli2.jsonc: ignores must exclude docs/testing/phase*_coverage_ledger.md" "Markdown generated ledger exclusion"

markdown_fix_repo="$(make_policy_repo)"
node - "$markdown_fix_repo/.markdownlint-cli2.jsonc" <<'NODE'
const fs = require("node:fs");
const file = process.argv[2];
const config = JSON.parse(fs.readFileSync(file, "utf8"));
config.fix = true;
fs.writeFileSync(file, `${JSON.stringify(config, null, 2)}\n`);
NODE
expect_policy_failure "$markdown_fix_repo" ".markdownlint-cli2.jsonc: fix must not be enabled" "Markdown lint fix disabled"

markdown_line_length_repo="$(make_policy_repo)"
node - "$markdown_line_length_repo/.markdownlint-cli2.jsonc" <<'NODE'
const fs = require("node:fs");
const file = process.argv[2];
const config = JSON.parse(fs.readFileSync(file, "utf8"));
config.config.MD013 = true;
fs.writeFileSync(file, `${JSON.stringify(config, null, 2)}\n`);
NODE
expect_policy_failure "$markdown_line_length_repo" ".markdownlint-cli2.jsonc: config.MD013 must be disabled" "Markdown line length disabled"

broad_policy_repo="$(make_policy_repo)"
cat >"$broad_policy_repo/tools/generated_artifact_policy.json" <<'JSON'
{
  "schema_id": "cartulary.generated_artifact_policy.v1",
  "generated_roots": [
    {
      "path": "internal",
      "allowed_extensions": [".go"],
      "required_marker": "^// Code generated .* DO NOT EDIT\\.$"
    }
  ],
  "generated_files": []
}
JSON
expect_policy_failure "$broad_policy_repo" "generated_roots[1].path is too broad for a generated root" "broad generated root"

escaping_policy_repo="$(make_policy_repo)"
cat >"$escaping_policy_repo/tools/generated_artifact_policy.json" <<'JSON'
{
  "schema_id": "cartulary.generated_artifact_policy.v1",
  "generated_roots": [
    {
      "path": "../internal/gen",
      "allowed_extensions": [".go"],
      "required_marker": "^// Code generated .* DO NOT EDIT\\.$"
    }
  ],
  "generated_files": []
}
JSON
expect_policy_failure "$escaping_policy_repo" "generated_roots[1].path must stay under the repository root" "escaping generated root"

duplicate_policy_repo="$(make_policy_repo)"
cat >"$duplicate_policy_repo/tools/generated_artifact_policy.json" <<'JSON'
{
  "schema_id": "cartulary.generated_artifact_policy.v1",
  "generated_roots": [
    {
      "path": "internal/gen",
      "allowed_extensions": [".go"],
      "required_marker": "^// Code generated .* DO NOT EDIT\\.$"
    },
    {
      "path": "internal/gen",
      "allowed_extensions": [".go"],
      "required_marker": "^// Code generated .* DO NOT EDIT\\.$"
    }
  ],
  "generated_files": []
}
JSON
expect_policy_failure "$duplicate_policy_repo" "duplicate generated root internal/gen" "duplicate generated root"

vet_scratch="$(cartulary_harness_mktemp_dir go-vet-generated.XXXXXX)"
cleanup_paths+=("$vet_scratch")
fake_go="$vet_scratch/go"
vet_args_log="$vet_scratch/vet-args.log"
cat >"$fake_go" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

case "${1:-}" in
  list)
    cat <<'PACKAGES'
github.com/JochiRaider/cartulary/cmd/server
github.com/JochiRaider/cartulary/cmd/operator
github.com/JochiRaider/cartulary/internal/gen/contracts
github.com/JochiRaider/cartulary/internal/gen/sql
github.com/JochiRaider/cartulary/internal/modules/auth
PACKAGES
    ;;
  vet)
    shift
    printf '%s\n' "$@" >"${FAKE_GO_VET_ARGS_LOG:?}"
    ;;
  *)
    echo "unexpected go invocation: $*" >&2
    exit 97
    ;;
esac
EOF
chmod +x "$fake_go"

GO="$fake_go" \
  GO_CACHE_DIR="$vet_scratch/go-cache" \
  GO_MOD_CACHE_DIR="$vet_scratch/go-mod-cache" \
  FAKE_GO_VET_ARGS_LOG="$vet_args_log" \
  bash "$VET_WRAPPER"

vet_args="$(cat "$vet_args_log")"
assert_contains "$vet_args" "github.com/JochiRaider/cartulary/cmd/server" "go vet authored cmd package"
assert_contains "$vet_args" "github.com/JochiRaider/cartulary/cmd/operator" "go vet authored operator cmd package"
assert_contains "$vet_args" "github.com/JochiRaider/cartulary/internal/modules/auth" "go vet authored module package"
assert_not_contains "$vet_args" "github.com/JochiRaider/cartulary/internal/gen/contracts" "go vet generated contracts exclusion"
assert_not_contains "$vet_args" "github.com/JochiRaider/cartulary/internal/gen/sql" "go vet generated sql exclusion"
