# Code generated by scripts/render-task-surface-make.mjs; DO NOT EDIT.

.PHONY: help help-all doctor bootstrap bootstrap-node-runtime frontend-toolchain frontend-install frontend-install-ci playwright-install db-up db-reset services-up services-wait postgres-wait minio-wait minio-init dev codegen-toolchain generate generate-artifacts generate-drift toolchain-drift migration-drift deployable-shape phase-map-check phase-ledgers phase-ledger-drift phase-schedules phase-schedule-drift benchmark-claim-check task-surface-report task-surface-check backend-unit backend-store backend-integration backend-integration-support backend-process target-plan target-plan-json fixture-report explain-run explain-target go-test-duration-baselines go-test-duration-baseline-coverage go-test-duration-baseline-drift browser-e2e-duration-baseline-drift backend-task-surface-check service-backed-unit-check test-service-images run-harness-smoke-fast run-harness-smoke-extended run-harness-smoke-full phase-test-name-check frontend-typecheck frontend-unit frontend-task-surface-check lint-biome format format-frontend browser-e2e browser-e2e-webserver-backed browser-e2e-functional browser-e2e-support browser-e2e-stateful browser-e2e-resettable browser-e2e-measurement browser-e2e-visual browser-e2e-task-surface-check test-local test-service-backed test-fast test-fast-service-backed test lint lint-go check check-setup-blockers check-static-validation check-harness-smoke check-build-prereqs check-local-product check-go-test-duration-baseline-drift check-browser-e2e-duration-baseline-drift check-frontend-unit check-meta-validation check-service-backed ci release-check license-report sbom build build-server build-migrate build-web clean distclean

TASK_SURFACE_HELP_LINES := \
	'Cartulary daily task surface' \
	'' \
	'daily:' \
	'  make help                           print the daily root task surface' \
	'  make help-all                       print the exhaustive public task surface' \
	'  make doctor                         verify required local tools and versions' \
	'  make bootstrap                      install pinned tools and frontend/browser dependencies' \
	'  make db-up                          start local Postgres and MinIO, then initialize the default MinIO bucket' \
	'  make db-reset                       recreate the local database only; does not reset object storage' \
	'  make dev                            run the Go server and Vite dev server' \
	'  make generate                       regenerate sqlc and contract-derived outputs' \
	'  make format                         format authored frontend sources' \
	'  make test-fast                      run the narrower local verification loop' \
	'  make test                           run the authoritative full test corpus' \
	'  make lint                           run backend and frontend lint/type checks' \
	'  make check                          run the developer verification gate' \
	'  make build                          build backend binaries with embedded web assets' \
	'  make clean                          remove repo-local build and report artifacts' \
	'' \
	'For all public targets, run: make help-all' \
	'For private/check internals, run: make task-surface-report TASK_SURFACE_REPORT_ARGS=--all' \
	''

TASK_SURFACE_HELP_ALL_LINES := \
	'Cartulary public task surface' \
	'' \
	'daily:' \
	'  make help                           print the daily root task surface' \
	'  make help-all                       print the exhaustive public task surface' \
	'  make doctor                         verify required local tools and versions' \
	'  make bootstrap                      install pinned tools and frontend/browser dependencies' \
	'  make db-up                          start local Postgres and MinIO, then initialize the default MinIO bucket' \
	'  make db-reset                       recreate the local database only; does not reset object storage' \
	'  make dev                            run the Go server and Vite dev server' \
	'  make generate                       regenerate sqlc and contract-derived outputs' \
	'  make format                         format authored frontend sources' \
	'  make test-fast                      run the narrower local verification loop' \
	'  make test                           run the authoritative full test corpus' \
	'  make lint                           run backend and frontend lint/type checks' \
	'  make check                          run the developer verification gate' \
	'  make build                          build backend binaries with embedded web assets' \
	'  make clean                          remove repo-local build and report artifacts' \
	'' \
	'diagnostics:' \
	'  make backend-unit                   run pure backend unit evidence' \
	'  make backend-store                  run service-backed store-domain evidence' \
	'  make backend-integration            run backend integration evidence' \
	'  make backend-process                run backend process evidence' \
	'  make target-plan                    explain backend target execution families' \
	'  make target-plan-json               emit deterministic backend target plan JSON' \
	'  make fixture-report                 RESULTS_DIR=<root|run-dir> report fixture cost hotspots' \
	'  make explain-run                    RESULTS_DIR=<root|run-dir> inspect run summary artifacts' \
	'  make explain-target                 TARGET=backend-store explain one backend target' \
	'  make frontend-typecheck             run TypeScript type checking' \
	'  make frontend-unit                  run the frontend unit suite' \
	'  make lint-biome                     run authored frontend Biome checks' \
	'  make browser-e2e                    run isolated browser E2E suites through one batch stack' \
	'  make browser-e2e-webserver-backed   run shared-stack browser E2E batch' \
	'  make browser-e2e-stateful           run isolated stateful browser E2E batch' \
	'  make browser-e2e-measurement        run ordinary browser measurement evidence' \
	'  make browser-e2e-visual             run isolated visual browser E2E' \
	'  make task-surface-report            print the root Make task-surface inventory' \
	'' \
	'baselines:' \
	'  make go-test-duration-baselines     RESULTS_DIR=<dir> refresh Go test duration baselines' \
	'  make go-test-duration-baseline-coverage verify Go shard baseline coverage' \
	'  make go-test-duration-baseline-drift RESULTS_DIR=<dir> verify Go shard baseline freshness' \
	'  make browser-e2e-duration-baseline-drift RESULTS_DIR=<dir> verify browser spec baseline freshness' \
	'  make benchmark-claim-check          validate retained Core 05 benchmark claim artifacts' \
	'' \
	'release:' \
	'  make ci                             run the provider-neutral CI entrypoint' \
	'  make release-check                  run check, extended harness, release artifacts, and build verification' \
	'  make build-server                   build the server binary' \
	'  make build-migrate                  build the migration binary' \
	'  make build-web                      build frontend web assets' \
	'  make distclean                      also remove repo-local tool/runtime caches' \
	'' \
	'advanced phase tooling:' \
	'  make bootstrap-node-runtime         install the pinned repo-local Node runtime' \
	'  make frontend-toolchain             verify the pinned Node/pnpm toolchain' \
	'  make frontend-install               install workspace dependencies' \
	'  make playwright-install             install browser dependencies' \
	'  make services-up                    start local Postgres and MinIO, then wait until ready' \
	'  make minio-init                     create the default local MinIO bucket if needed' \
	'  make generate-drift                 fail on generated artifact drift' \
	'  make toolchain-drift                fail on repo-control toolchain pin drift' \
	'  make migration-drift                verify migrations against a scratch database' \
	'  make phase-ledgers                  regenerate committed phase coverage ledgers' \
	'  make phase-ledger-drift             fail on phase coverage ledger drift' \
	'  make phase-schedules                regenerate committed phase-derived schedules' \
	'  make phase-schedule-drift           fail on phase-derived schedule drift' \
	''

