# Code generated by scripts/render-task-surface-make.mjs; DO NOT EDIT.

.PHONY: help help-all doctor bootstrap bootstrap-node-runtime frontend-toolchain frontend-install frontend-install-ci playwright-install db-up db-reset services-up services-wait postgres-wait minio-wait minio-init dev codegen-toolchain generate generate-artifacts generate-drift toolchain-drift migration-drift deployable-shape phase-map-check phase-ledgers phase-ledger-drift phase-schedules phase-schedule-drift benchmark-claim-check task-surface-report task-guide task-surface-check backend-unit backend-store backend-integration backend-integration-support backend-process target-plan target-plan-json fixture-report explain-run explain-phase explain-target go-test-duration-baselines go-test-duration-baseline-coverage go-test-duration-baseline-drift browser-e2e-duration-baseline-drift scheduler-event-order-drift backend-task-surface-check service-backed-unit-check test-service-images run-harness-smoke-fast run-harness-smoke-extended run-harness-smoke-full phase-test-name-check frontend-typecheck frontend-unit frontend-task-surface-check lint-biome format format-frontend browser-e2e browser-e2e-webserver-backed browser-e2e-functional browser-e2e-support browser-e2e-stateful browser-e2e-resettable browser-e2e-measurement browser-e2e-visual browser-e2e-task-surface-check test-local test-service-backed test-fast test-fast-service-backed test lint lint-go check check-setup-blockers check-harness-smoke check-build-prereqs check-go-test-duration-baseline-drift check-browser-e2e-duration-baseline-drift check-frontend-unit check-service-backed ci release-check license-report sbom build build-server build-migrate build-web clean distclean

TASK_SURFACE_HELP_LINES := \
	'Cartulary compact workflow task surface' \
	'' \
	'compact:' \
	'  make help                           print the compact workflow task surface' \
	'  make task-guide                     recommend targets by role, phase, services, and artifacts' \
	'  make doctor                         verify required local tools and versions' \
	'  make bootstrap                      install pinned tools and frontend/browser dependencies' \
	'  make db-up                          start local Postgres and MinIO, then initialize the default MinIO bucket' \
	'  make db-reset                       recreate the local database only; does not reset object storage' \
	'  make dev                            run the Go server and Vite dev server' \
	'  make generate                       regenerate sqlc and contract-derived outputs' \
	'  make format                         format authored frontend sources' \
	'  make test-fast                      run the narrower local verification loop' \
	'  make check                          run the developer verification gate' \
	'  make clean                          remove repo-local build and report artifacts' \
	'' \
	'For all public targets, run: make help-all' \
	'For private/check internals, run: make task-surface-report TASK_SURFACE_REPORT_ARGS=--all' \
	''

TASK_SURFACE_HELP_ALL_LINES := \
	'Cartulary public task surface' \
	'' \
	'local dev:' \
	'  make help                           print the compact workflow task surface' \
	'  make help-all                       print the exhaustive public workflow task surface' \
	'  make doctor                         verify required local tools and versions' \
	'  make bootstrap                      install pinned tools and frontend/browser dependencies' \
	'  make bootstrap-node-runtime         install the pinned repo-local Node runtime' \
	'  make frontend-toolchain             verify the pinned Node/pnpm toolchain' \
	'  make frontend-install               install workspace dependencies' \
	'  make playwright-install             install browser dependencies' \
	'  make db-up                          start local Postgres and MinIO, then initialize the default MinIO bucket' \
	'  make db-reset                       recreate the local database only; does not reset object storage' \
	'  make services-up                    start local Postgres and MinIO, then wait until ready' \
	'  make minio-init                     create the default local MinIO bucket if needed' \
	'  make dev                            run the Go server and Vite dev server' \
	'  make generate                       regenerate sqlc and contract-derived outputs' \
	'  make format                         format authored frontend sources' \
	'  make clean                          remove repo-local build and report artifacts' \
	'' \
	'fast verification:' \
	'  make test-fast                      run the narrower local verification loop' \
	'  make backend-unit                   run pure backend unit evidence' \
	'  make backend-store                  run service-backed store-domain evidence' \
	'  make backend-integration            run backend integration evidence' \
	'  make backend-process                run backend process evidence' \
	'  make frontend-typecheck             run TypeScript type checking' \
	'  make frontend-unit                  run the frontend unit suite' \
	'  make lint                           run backend and frontend lint/type checks' \
	'  make lint-biome                     run authored frontend Biome checks' \
	'' \
	'full gates:' \
	'  make test                           run the authoritative full test corpus' \
	'  make check                          run the developer verification gate' \
	'  make browser-e2e                    run isolated browser E2E suites through one batch stack' \
	'  make browser-e2e-webserver-backed   run shared-stack browser E2E batch' \
	'  make browser-e2e-stateful           run isolated stateful browser E2E batch' \
	'  make browser-e2e-measurement        run ordinary browser measurement evidence' \
	'  make browser-e2e-visual             run isolated visual browser E2E' \
	'' \
	'investigate a run:' \
	'  make task-guide                     ROLE=feature-dev PHASE=phase2 recommend what to run' \
	'  make task-surface-report            print the root Make task-surface inventory' \
	'  make target-plan                    explain backend target execution families' \
	'  make target-plan-json               emit deterministic backend target plan JSON' \
	'  make explain-phase                  PHASE=phase2 explain phase evidence and target coverage' \
	'  make explain-target                 TARGET=backend-store DETAIL=rows explain one target' \
	'  make explain-run                    RESULTS_DIR=<root|run-dir> inspect run summary artifacts' \
	'  make fixture-report                 RESULTS_DIR=<root|run-dir> report fixture cost hotspots' \
	'' \
	'phase maintenance:' \
	'  make generate-drift                 fail on generated artifact drift' \
	'  make toolchain-drift                fail on repo-control toolchain pin drift' \
	'  make migration-drift                verify migrations against a scratch database' \
	'  make phase-ledgers                  regenerate committed phase coverage ledgers' \
	'  make phase-ledger-drift             fail on phase coverage ledger drift' \
	'  make phase-schedules                regenerate committed phase-derived schedules' \
	'  make phase-schedule-drift           fail on phase-derived schedule drift' \
	'  make benchmark-claim-check          validate retained Core 05 benchmark claim artifacts' \
	'  make go-test-duration-baselines     RESULTS_DIR=<dir> refresh Go test duration baselines' \
	'  make go-test-duration-baseline-coverage verify Go shard baseline coverage' \
	'  make go-test-duration-baseline-drift RESULTS_DIR=<dir> verify Go shard baseline freshness' \
	'  make browser-e2e-duration-baseline-drift RESULTS_DIR=<dir> verify browser spec baseline freshness' \
	'  make scheduler-event-order-drift    RESULTS_DIR=<dir> verify scheduler event stream ordering' \
	'' \
	'release:' \
	'  make ci                             run the provider-neutral CI entrypoint' \
	'  make release-check                  run check, extended harness, release artifacts, and build verification' \
	'  make build                          build backend binaries with embedded web assets' \
	'  make build-server                   build the server binary' \
	'  make build-migrate                  build the migration binary' \
	'  make build-web                      build frontend web assets' \
	'  make distclean                      also remove repo-local tool/runtime caches' \
	''

test-fast: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) $(TEST_SERVICES_BIN)
	$(Q)MAKE="$(MAKE)" NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" $(RUN_MAKE_SEQUENCE_SCRIPT) --sequence test-fast

test: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP)
	$(Q)MAKE="$(MAKE)" NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" $(RUN_MAKE_SEQUENCE_SCRIPT) --sequence test

ci: export CI := 1
ci: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP)
	$(Q)MAKE="$(MAKE)" NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" $(RUN_MAKE_SEQUENCE_SCRIPT) --sequence ci

release-check: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP)
	$(Q)MAKE="$(MAKE)" NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" $(RUN_MAKE_SEQUENCE_SCRIPT) --sequence release-check

check: $(NODE_BIN)
	$(Q)MAKE="$(MAKE)" NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" $(NODE_BIN) $(RUN_CHECK_SCHEDULE_SCRIPT) --target check --manifest "$(CHECK_SCHEDULE_MANIFEST)" --resource-limit host_cpu=$(CHECK_HOST_CPU_JOBS) --resource-limit host_io=$(CHECK_HOST_IO_JOBS)

run-harness-smoke-fast: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP)
	$(Q)NODE_BIN=$(NODE_BIN) TEST_OUTPUT_SCRIPT=$(TEST_OUTPUT_SCRIPT) TASK_SURFACE_MANIFEST=$(TASK_SURFACE_MANIFEST) $(NODE_BIN) $(RUN_HARNESS_SMOKE_SCRIPT) --tier fast --jobs "$(HARNESS_SMOKE_JOBS)"

run-harness-smoke-extended: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP)
	$(Q)NODE_BIN=$(NODE_BIN) TEST_OUTPUT_SCRIPT=$(TEST_OUTPUT_SCRIPT) TASK_SURFACE_MANIFEST=$(TASK_SURFACE_MANIFEST) $(NODE_BIN) $(RUN_HARNESS_SMOKE_SCRIPT) --tier extended --jobs "$(HARNESS_SMOKE_JOBS)"

run-harness-smoke-full: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP)
	$(Q)NODE_BIN=$(NODE_BIN) TEST_OUTPUT_SCRIPT=$(TEST_OUTPUT_SCRIPT) TASK_SURFACE_MANIFEST=$(TASK_SURFACE_MANIFEST) $(NODE_BIN) $(RUN_HARNESS_SMOKE_SCRIPT) --tier full --jobs "$(HARNESS_SMOKE_JOBS)"

phase-test-name-check: $(NODE_BIN)
	$(RUN_PHASE) "phase-test-name-check" -- $(NODE_BIN) ./scripts/check-phase-test-names.mjs

browser-e2e-task-surface-check:
	$(RUN_PHASE) "browser-e2e-task-surface-check" -- ./scripts/check-browser-e2e-task-surface.sh

frontend-task-surface-check: $(NODE_BIN)
	$(RUN_PHASE) "frontend-task-surface-check" -- env NODE_BIN=$(NODE_BIN) ./scripts/check-frontend-task-surface.sh

backend-task-surface-check: $(NODE_BIN)
	$(RUN_PHASE) "backend-task-surface-check" -- env NODE_BIN=$(NODE_BIN) ./scripts/check-backend-task-surface.sh

service-backed-unit-check:
	$(RUN_PHASE) "service-backed-unit-check" -- ./scripts/check-service-backed-unit-tests.sh

test-fast-service-backed: export CARTULARY_TEST_TARGET := test-fast-service-backed
test-fast-service-backed: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server $(TEST_SERVICES_BIN) test-service-images
	$(Q)env NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" TEST_SERVICES_BIN="$(TEST_SERVICES_BIN)" RUN_PHASE_SCRIPT="$(RUN_PHASE_SCRIPT)" RUN_SERVICE_BACKED_SCHEDULE_SCRIPT="$(RUN_SERVICE_BACKED_SCHEDULE_SCRIPT)" SERVICE_BACKED_SCHEDULE_MANIFEST="$(SERVICE_BACKED_SCHEDULE_MANIFEST)" CARTULARY_RUNNER_SCRIPT="$(CARTULARY_RUNNER_SCRIPT)" $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) service-backed-target --target test-fast-service-backed --phase-label "test-fast service-backed" --service-wrapper test-services

test-service-backed: export CARTULARY_TEST_TARGET := test-service-backed
test-service-backed: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate $(TEST_SERVICES_BIN) test-service-images
	$(Q)env NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" TEST_SERVICES_BIN="$(TEST_SERVICES_BIN)" RUN_PHASE_SCRIPT="$(RUN_PHASE_SCRIPT)" RUN_SERVICE_BACKED_SCHEDULE_SCRIPT="$(RUN_SERVICE_BACKED_SCHEDULE_SCRIPT)" SERVICE_BACKED_SCHEDULE_MANIFEST="$(SERVICE_BACKED_SCHEDULE_MANIFEST)" CARTULARY_RUNNER_SCRIPT="$(CARTULARY_RUNNER_SCRIPT)" $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) service-backed-target --target test-service-backed --phase-label "test service-backed" --service-wrapper test-services

backend-unit: export CARTULARY_TEST_TARGET := backend-unit
backend-unit: $(NODE_BIN)
	$(Q)env GO=$(GO) GO_CACHE_DIR=$(GO_CACHE_DIR) GO_MOD_CACHE_DIR=$(GO_MOD_CACHE_DIR) NODE_BIN=$(NODE_BIN) GO_TEST_SERVICE_PACKAGE_PARALLELISM=$(GO_TEST_SERVICE_PACKAGE_PARALLELISM) $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) go-target backend-unit

backend-store: export CARTULARY_TEST_TARGET := backend-store
backend-store: $(NODE_BIN) $(TEST_SERVICES_BIN) test-service-images
	$(Q)env GO=$(GO) GO_CACHE_DIR=$(GO_CACHE_DIR) GO_MOD_CACHE_DIR=$(GO_MOD_CACHE_DIR) NODE_BIN=$(NODE_BIN) GO_TEST_PACKAGE_PARALLELISM=$(EFFECTIVE_BACKEND_STORE_GO_TEST_P) GO_TEST_SERVICE_PACKAGE_PARALLELISM=$(GO_TEST_SERVICE_PACKAGE_PARALLELISM) $(TEST_SERVICES_BIN) run -- $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) go-target backend-store

backend-integration: export CARTULARY_TEST_TARGET := backend-integration
backend-integration: $(NODE_BIN) $(TEST_SERVICES_BIN) test-service-images
	$(Q)env GO=$(GO) GO_CACHE_DIR=$(GO_CACHE_DIR) GO_MOD_CACHE_DIR=$(GO_MOD_CACHE_DIR) NODE_BIN=$(NODE_BIN) GO_TEST_PACKAGE_PARALLELISM=$(EFFECTIVE_BACKEND_INTEGRATION_GO_TEST_P) BACKEND_INTEGRATION_SHARD_JOBS=$(BACKEND_INTEGRATION_SHARD_JOBS) GO_TEST_SERVICE_PACKAGE_PARALLELISM=$(GO_TEST_SERVICE_PACKAGE_PARALLELISM) $(TEST_SERVICES_BIN) run -- $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) go-target backend-integration

backend-integration-support: export CARTULARY_TEST_TARGET := backend-integration-support
backend-integration-support: $(NODE_BIN) $(TEST_SERVICES_BIN) test-service-images
	$(Q)env GO=$(GO) GO_CACHE_DIR=$(GO_CACHE_DIR) GO_MOD_CACHE_DIR=$(GO_MOD_CACHE_DIR) NODE_BIN=$(NODE_BIN) GO_TEST_PACKAGE_PARALLELISM=$(EFFECTIVE_BACKEND_INTEGRATION_GO_TEST_P) BACKEND_INTEGRATION_SHARD_JOBS=$(BACKEND_INTEGRATION_SHARD_JOBS) GO_TEST_SERVICE_PACKAGE_PARALLELISM=$(GO_TEST_SERVICE_PACKAGE_PARALLELISM) $(TEST_SERVICES_BIN) run -- $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) go-target backend-integration-support

# Phase 0 process evidence is part of the developer gate and must never be direct-run only.
backend-process: export CARTULARY_TEST_TARGET := backend-process
backend-process: $(NODE_BIN) build-server $(TEST_SERVICES_BIN) test-service-images
	$(Q)env GO=$(GO) GO_CACHE_DIR=$(GO_CACHE_DIR) GO_MOD_CACHE_DIR=$(GO_MOD_CACHE_DIR) NODE_BIN=$(NODE_BIN) CARTULARY_SERVER_BIN=$(SERVER_BIN) GO_TEST_SERVICE_PACKAGE_PARALLELISM=$(GO_TEST_SERVICE_PACKAGE_PARALLELISM) $(TEST_SERVICES_BIN) run -- $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) go-target backend-process

browser-e2e: export CARTULARY_TEST_TARGET := browser-e2e
browser-e2e: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate $(TEST_SERVICES_BIN) test-service-images
	$(Q)env $(BROWSER_E2E_OWNED_STACK_ENV) TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" PLAYWRIGHT_WORKERS=1 $(TEST_SERVICES_BIN) run -- ./scripts/run-browser-e2e-target.sh isolated

browser-e2e-webserver-backed: export CARTULARY_TEST_TARGET := browser-e2e-webserver-backed
browser-e2e-webserver-backed: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate
	$(Q)env $(BROWSER_E2E_OWNED_STACK_ENV) TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" PLAYWRIGHT_WORKERS=$(PLAYWRIGHT_WORKERS) ./scripts/run-browser-e2e-target.sh webserver-backed

browser-e2e-functional: export CARTULARY_TEST_TARGET := browser-e2e-functional
browser-e2e-functional: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate
	$(Q)env $(BROWSER_E2E_OWNED_STACK_ENV) TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" PLAYWRIGHT_WORKERS=$(PLAYWRIGHT_WORKERS) ./scripts/run-browser-e2e-target.sh functional

browser-e2e-support: export CARTULARY_TEST_TARGET := browser-e2e-support
browser-e2e-support: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate
	$(Q)env $(BROWSER_E2E_OWNED_STACK_ENV) TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" PLAYWRIGHT_WORKERS=$(PLAYWRIGHT_WORKERS) ./scripts/run-browser-e2e-target.sh support

# Browser evidence that mutates process-global backend state belongs here.
browser-e2e-stateful: export CARTULARY_TEST_TARGET := browser-e2e-stateful
browser-e2e-stateful: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate
	$(Q)env $(BROWSER_E2E_OWNED_STACK_ENV) TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" PLAYWRIGHT_WORKERS=1 ./scripts/run-browser-e2e-target.sh stateful

browser-e2e-resettable: export CARTULARY_TEST_TARGET := browser-e2e-resettable
browser-e2e-resettable: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate
	$(Q)env $(BROWSER_E2E_OWNED_STACK_ENV) TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" PLAYWRIGHT_WORKERS=1 ./scripts/run-browser-e2e-target.sh resettable

# Ordinary implementation/regression measurement; not claim-bearing Core 05 publication evidence.
browser-e2e-measurement: export CARTULARY_TEST_TARGET := browser-e2e-measurement
browser-e2e-measurement: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate
	$(Q)env $(BROWSER_E2E_OWNED_STACK_ENV) TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" PLAYWRIGHT_WORKERS=1 ./scripts/run-browser-e2e-target.sh measurement

browser-e2e-visual: export CARTULARY_TEST_TARGET := browser-e2e-visual
browser-e2e-visual: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate
	$(Q)env $(BROWSER_E2E_OWNED_STACK_ENV) TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" PLAYWRIGHT_WORKERS=1 ./scripts/run-browser-e2e-target.sh visual

check-go-test-duration-baseline-drift:
	$(Q)env MAKE_BIN="$(MAKE)" NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" RUN_PHASE_SCRIPT="$(RUN_PHASE_SCRIPT)" $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) summary-target --target check-go-test-duration-baseline-drift --child-target go-test-duration-baseline-drift --status pass --phase-label "check-go-test-duration-baseline-drift child go-test-duration-baseline-drift"

check-browser-e2e-duration-baseline-drift:
	$(Q)env MAKE_BIN="$(MAKE)" NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" RUN_PHASE_SCRIPT="$(RUN_PHASE_SCRIPT)" $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) summary-target --target check-browser-e2e-duration-baseline-drift --child-target browser-e2e-duration-baseline-drift --status pass --phase-label "check-browser-e2e-duration-baseline-drift child browser-e2e-duration-baseline-drift"

check-service-backed: export CARTULARY_TEST_TARGET := check-service-backed
check-service-backed: $(NODE_BIN) $(FRONTEND_INSTALL_STAMP) build-server build-migrate test-service-images
	$(Q)env NODE_BIN="$(NODE_BIN)" TEST_OUTPUT_SCRIPT="$(TEST_OUTPUT_SCRIPT)" TASK_SURFACE_MANIFEST="$(TASK_SURFACE_MANIFEST)" TEST_SERVICES_BIN="$(TEST_SERVICES_BIN)" RUN_PHASE_SCRIPT="$(RUN_PHASE_SCRIPT)" RUN_SERVICE_BACKED_SCHEDULE_SCRIPT="$(RUN_SERVICE_BACKED_SCHEDULE_SCRIPT)" SERVICE_BACKED_SCHEDULE_MANIFEST="$(SERVICE_BACKED_SCHEDULE_MANIFEST)" CARTULARY_RUNNER_SCRIPT="$(CARTULARY_RUNNER_SCRIPT)" $(NODE_BIN) $(CARTULARY_RUNNER_SCRIPT) service-backed-target --target check-service-backed --phase-label "check service-backed" --service-wrapper test-services

task-surface-check: $(NODE_BIN)
	$(RUN_PHASE) "task-surface-check" -- $(NODE_BIN) ./scripts/print-task-surface-report.mjs --check

