import { readFileSync } from "node:fs";

import { validateSchemaSync } from "../../contract/index.mjs";

const schemaID = "cartulary.design_token_registry.v1";

export class DesignTokenValidationError extends Error {
  constructor(failures) {
    super(
      `design token validation failed: ${failures
        .map((failure) => `${failure.class}: ${failure.message}`)
        .join("; ")}`,
    );
    this.name = "DesignTokenValidationError";
    this.failures = failures;
  }
}

function tokenNamespace(variableName) {
  const first = variableName.slice("--ct-".length).split("-")[0];
  return first === "component" ? "components" : first;
}

export function loadDesignTokenDocument(filePath) {
  let registry;
  try {
    registry = JSON.parse(readFileSync(filePath, "utf8"));
    validateSchemaSync(schemaID, registry);
  } catch (error) {
    throw new DesignTokenValidationError([
      {
        class: "invalid_machine_registry",
        message: `${filePath}: ${error instanceof Error ? error.message : String(error)}`,
      },
    ]);
  }

  const entries = Object.entries(registry.token_vars).sort(([left], [right]) =>
    left.localeCompare(right),
  );
  return {
    metadata: {
      defaultThemeId: registry.default_theme_id,
      ownerId: registry.owner_id,
      verificationId: registry.verification_id,
    },
    tokenMap: new Map(
      entries.map(([name, raw]) => [
        name,
        { name, namespace: tokenNamespace(name), raw },
      ]),
    ),
    tokenVars: new Map(entries),
  };
}

export function renderDesignTokenTypeScript(document) {
  const tokenVarEntries = [...document.tokenVars.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );
  const cssText = renderCssText(document.metadata.defaultThemeId, tokenVarEntries);
  const tokenVarObject = Object.fromEntries(tokenVarEntries);

  return [
    "// Code generated by cartulary.design_token_generation.v1; DO NOT EDIT.",
    "",
    `export const cartularyDefaultThemeId = ${JSON.stringify(document.metadata.defaultThemeId)} as const;`,
    "",
    `export const cartularyDesignTokenVars = ${stableJSONStringify(tokenVarObject)} as const;`,
    "",
    `export const cartularyDesignThemeCssText = ${JSON.stringify(cssText)} as const;`,
    "",
    "export type CartularyDesignTokenVarName = keyof typeof cartularyDesignTokenVars;",
    "export type CartularyDefaultThemeId = typeof cartularyDefaultThemeId;",
    "",
  ].join("\n");
}

function renderCssText(themeId, tokenVarEntries) {
  const declarations = tokenVarEntries.map(([name, value]) => `  ${name}: ${value};`);
  return [`:root,`, `[data-cartulary-theme="${themeId}"] {`, ...declarations, `}`].join("\n");
}

function stableJSONStringify(value) {
  return JSON.stringify(value, Object.keys(value).sort(), 2);
}
